### ISSUE TITLE
Submission Template

### ISSUE THREAD

**Issue by elyseholladay** [SassConf/2015-austin-speaker-cfp#1]
**You can copy the raw template here: https://github.com/SassConf/2015-austin-speaker-cfp/blob/master/docs/submission-template.md**
# Title of Presentation (required)
## Type of Presentation (required)

[  ] Standard Length Talk
[  ] Lightning Talk
[  ] Workshop
[  ] Moderated Discussion
## Description (required)

[A description of your presentation goes here. Please don't give us a 140 character elevator pitch—tell us what you want to talk about. Give us an outline. Bullet points. A long rambly description of an idea. Tell us your dreams.

Fine Print:
- If you're selected, we'll help you write up an Official Description that can go on the website, so don't worry about that.
- Please don’t say, “I know it’s not that good/been done before/is a half baked idea!” You’re great and so is your submission!
- Here is where you can include any bonus materials, if you have them. Having or not having bonus materials will _not_ affect your submission.

If you are submitting a Moderated Discussion, please write about the topic you want to discuss in your small group.]
### Workshops: Coding Exercise (required for workshops only)

[If you are submitting a workshop, please write a few sentences about the type of coding exercise you’ll be having attendees work on during your workshop.]
### Moderated Discussions: Topic & Questions (required for discussions only)

[If you are suggesting a Moderated Discussion, please write a few questions about your topic that you’d like to ask your small group, or the types of questions you hope to get re: your topic.]
## Speaker Info (required)
- Name      : Carol Danvers
- Location  : NYC, NY
- Contact   : msmarvel@avengers.com
##### Social Media:
- Twitter   : [@msmarvel](url to twitter account)
- GitHub    : [msmarvel](url to GitHub account)
- Url(s)    : [msmarvel.com](url to relevant sites)
##### Bio:

I’m an example bio. I'm an ex-Air Force pilot superhero who possesses the powers of flight, super strength, invulnerability, and cosmic energy blasts. I love a good costume change and [a snarky one-liner](http://caroldanversspeaking.tumblr.com/).
##### Photo:

![avatar](http://41.media.tumblr.com/7a491658ca955d791a622130b175f5bf/tumblr_nhvw6w9Ceq1qdep0so1_500.jpg)

**Comment by xzyfer** [comment]
Might be worth showing the raw markup rather than the formatted output. 
Copying this template requires re-adding all the markup formatting (unless there is an easier way I'm unaware of).

**Comment by elyseholladay** [comment]
@xzyfer The template is also here, in raw: https://github.com/SassConf/2015-austin-speaker-cfp/blob/master/docs/submission-template.md although I will add that link in this sample issue as well! Thanks for the good idea!

**Comment by xzyfer** [comment]
Ah great! I figured you were on it. I should've looked harder. :+1:

**Comment by elyseholladay** [comment]
No problem :smile: There's a lot of stuff to read, something always slips through the cracks. Hopefully it's clearer now!
