### ISSUE TITLE
How to talk to humans: a different approach to soft skills

### ISSUE THREAD

**Issue by sharonsteed** [SassConf/2015-austin-speaker-cfp#11]
How to talk to humans: a different approach to soft skills
## Type of Presentation (required)

WORKSHOP
## Description (required)

Developers are trained to communicate to things with a goal in mind. When you're talking to a computer, you type in your code and it responds by giving you back what you want. Simple and straight forward. When talking to people? Not always the case. Why? Because talking to people requires a special set of skills - namely, empathy and a little bit of storytelling. In an industry filled with brilliant minds, great ideas and mass disruption, so few of the best and brightest know how to tell their compelling story. This workshop teaches you how.
## Speaker Info (required)
- Name      : Sharon Steed
- Location  : Pittsburgh, PA
- Contact   : Sharon@speechirl.com
##### Social Media:
- Twitter   : @sharonsteed
- GitHub    : sharonasteed
- Url(s)    : sharonsteed.co
##### Bio:

Sharon is the director of business development and marketing for speech IRL, a speech therapy practice delivering communication therapy and training.  She is a life-long stutterer that speaks about fear and vulnerability at the intersection of marketing, communication, business and tech. She has spoken to universities about stuttering, at Ignite Chicago about patience, Madison+ Ruby about branding and to a host of other audiences. 
##### Photo:

https://media.licdn.com/mpr/mpr/shrink_500_500/p/6/005/056/29b/1b43068.jpg

**Comment by elyseholladay** [comment]
Hi Sharon!

Thank you so much for submitting to SassConf this year!

Unfortunately, we weren’t able to select your workshop. 

We had an incredible number of submissions this year: 81, in fact, enough to fill up over two weeks of Sassy goodness! But we only have two days, and we couldn’t pick everything.

If you have any questions at all about our selection process, your submission, or anything else at all, please reach out: elyse@sassconf.com and I’ll gladly give you more details.

Again, thank you for submitting. It’s people like you, who are willing to put themselves out there and work hard and submit and give talks that make it possible to even have SassConf. I hope you will submit again next year and continue to be part of the Sass community!

See you in November!
