### ISSUE TITLE
What stuttering can teach you about marketing

### ISSUE THREAD

**Issue by sharonsteed** [SassConf/2015-austin-speaker-cfp#12]
# Title of Presentation (required)

What stuttering can teach you about marketing
## Type of Presentation (required)

STANDARD LENGTH TALK
## Description (required)

We’re all marketers – of our companies, our brands and ourselves. On the surface, we know what to do. Have a website. Hand out our business cards. Shake a lot of hands. And talk about the thing we want to be know (and hired) for. But there is a different level of marketing that can raise your exposure ten-fold. Unfortunately, most people don’t tap into it.

I’m Sharon, and I stutter. Because of my impediment, I had to get creative with how I communicated with people and presented myself. But after years of hiding it, I realized that the thing that made me different in a not-so-great way gave me the opportunity to be a more effective listener, have more empathy and communicate with others in ways that that I wouldn’t have thought of if it wasn’t for my speech impediment.
## Speaker Info (required)
- Name      : Sharon Steed
- Location  : Pittsburgh, PA
- Contact   : Sharon@speechirl.com
##### Social Media:
- Twitter   : @sharonsteed
- GitHub    : sharonasteed
- Url(s)    : sharonsteed.co
##### Bio:

Sharon is the director of business development and marketing for speech IRL, a speech therapy practice delivering communication therapy and training.  She is a life-long stutterer that speaks about fear and vulnerability at the intersection of marketing, communication, business and tech. She has spoken to universities about stuttering, at Ignite Chicago about patience, Madison+ Ruby about branding and to a host of other audiences. 
##### Photo:

https://media.licdn.com/mpr/mpr/shrink_500_500/p/6/005/056/29b/1b43068.jpg

**Comment by elyseholladay** [comment]
Hi Sharon!

Thank you so much for submitting to SassConf this year!

Unfortunately, we weren’t able to select your talk. 

We had an incredible number of submissions this year: 81, in fact, enough to fill up over two weeks of Sassy goodness! But we only have two days, and we couldn’t pick everything.

If you have any questions at all about our selection process, your submission, or anything else at all, please reach out: elyse@sassconf.com and I’ll gladly give you more details.

Again, thank you for submitting. It’s people like you, who are willing to put themselves out there and work hard and submit and give talks that make it possible to even have SassConf. I hope you will submit again next year and continue to be part of the Sass community!

See you in November!
