### ISSUE TITLE
Using Susy to Create Layouts Easily 

### ISSUE THREAD

**Issue by zellwk** [SassConf/2015-austin-speaker-cfp#13]
# Using Susy to Create Layouts Easily
## Type of Presentation (required)

[ ] Standard Length Talk
[ ] Lightning Talk
[X] Workshop
[ ] Moderated Discussion
## Description (required)

We have been stuck with the good old 12-column grid for far too long. Long gone are the days when we were limited to the 960 grid, where Bootstrap or Foundation ruled the frontend world. There's something new and powerful we can use to create layouts now. 

I got to know about Susy a year ago. Every other layout library or grid system I've encountered since then was nowhere as close and as flexible as Susy. 

But because Susy is so flexible, there is no set way to do anything. People pretty much have to pick it up and learn by trial and error. Many stumble when they are faced with more challenging grids.  

I want to help more people make the layouts they want and not feel restricted by existing grid frameworks. 

Bonus Material: 

I also written a book on [learning Susy](http://zell-weekeat.com/learnsusy). Everyone will get a free copy of the ebook and source code from the basic package. 
### Workshops: Coding Exercise (required for workshops only)

The workshop will involve the following:

1) Making sure everyone is able to install and run Susy on their system. 
2) Explaining what Susy is, how to create a basic layout and what goes on behind the scenes. This would help participants understand what is going on and find out that it's really all just floats and calculations. 
3) Actual coding walkthroughs will involve participants creating a simple layout, a nested grid layout and an asymmetric grid. This also makes sure that participants gets a good grasp of how to write HTML to allow them to breeze through the layout creation. 
4) We will end off by letting the participants grab a real example of a site they want to create and they work on it in groups, where I will facilitate and answer questions.

If there's any better way the workshop can be conducted, please feel free to let me know! It'll be good to explore :) 
## Speaker Info (required)
- Name      : Zell Liew
- Location  : Singapore
- Contact   : zellwk@gmail.com
##### Social Media:
- Twitter   : [@zellwk](https://twitter.com/zellwk)
- GitHub    : [msmarvel](https://github.com/zellwk)
- Url(s)    : [zell-weekeat.com](url to relevant sites)
##### Bio:

I'm Zell, a freelance frontend developer who specializes in using Susy for layouts. I have been working with Susy over the past year and helped many developers with their challenges on it. 

Aside from Susy, I love to tinker with Sass, create my own mixins and functions and explore how to make coding things easier and more efficient. 

Besides Susy, I also play around with JavaScript and build tools like Gulp and Grunt. 

If I'm not coding, you'll find me struggling to learn the guitar :) 
##### Photo:

![](http://www.zell-weekeat.com/wp-content/uploads/2015/05/D71_1763.jpg)

**Comment by scottkellum** [comment]
:+1: Sounds good. I think a lot of people in the Sass community use and love Susy or have heard about it and want to know more.

Working in groups on a single project might be difficult. How do you want people to work together? Would one person type the code while others huddle around and make suggestions? Would providing a challenge or website without any layout work along with specific goals to the people in the workshop be better?

**Comment by zellwk** [comment]
You're right, working in groups might be difficult. Working in pairs may be a better solution. The pair can exchange suggestions and come up with solutions they may not have thought of indivually. 

Providing a starter template with Susy would help the workshop go much smoother by letting everyone start on the same page. 

Let me knock out a rough timeline so I can dive into more details, and think of more concrete stuff.

We can walk through the basics of using Susy and creating a nested layout in the first 30mins. 

Next up can be a challenge to get participants to code a website that was chosen beforehand to ensure they understand the basic principles. This would use 20mins. 

Then we can do a quick 10min Q&A + break. 

The second hour can be similar to the first, this time we focus on responsive websites, media queries, susy-background grid, followed by another 20mins hands on and 10mins Q&A + break. 

Third hour can be similar again, this time focusing on isolation and asymmetric grids. 

For the fourth hour, we could do a vote to find out if participants would want to find out how to make Susy work with these 3 types of layouts

1) Stick (fixed-position) items 
2) Masonry 
3) Off canvas layouts 

I'm thinking this portion could be a code-along session where the groups will follow along. We can do this for 45mins and have a final 15min Q&A before we end the workshop. 

How does the breakdown sound?

**Comment by elyseholladay** [comment]
Hi Zell!

Thank you so much for submitting to SassConf this year!

Unfortunately, we weren’t able to select your workshop. 

We had an incredible number of submissions this year: 81, in fact, enough to fill up over two weeks of Sassy goodness! But we only have two days, and we couldn’t pick everything.

If you have any questions at all about our selection process, your submission, or anything else at all, please reach out: elyse@sassconf.com and I’ll gladly give you more details.

Again, thank you for submitting. It’s people like you, who are willing to put themselves out there and work hard and submit and give talks that make it possible to even have SassConf. I hope you will submit again next year and continue to be part of the Sass community!

See you in November!
