### ISSUE TITLE
DIY UX for Dev Teams: Building better products together

### ISSUE THREAD

**Issue by afknapping** [SassConf/2015-austin-speaker-cfp#15]
# DIY UX for Dev Teams: Building better products together
- Standard Length Talk
## Description

You are already »doing UX« if you are working on software. The next question is how to build better UX, amirite?

I'll try to provide an array of entry points to the topic so you can start to draw your own map and make controlled experiments. We will poke into a dozen+ methods and tools from the UX Design and Research communities – and also see why a good communication infrastructure in your team is vital for this kind of work.

If you value collaboration over delegation, this session will hopefully be interesting for you.
## Speaker Info (required)
- Name      : Fabian Fabian
- Location  : Hamburg, Germany
- Contact   : fabian@superpursuitmo.de
##### Social Media:
- Twitter   : [@filtercake](https://twitter.com/filtercake)
- GitHub    : [filtercake](https://github.com/filtercake)
- Url(s)    : [filtercake.com](http://filtercake.com)
##### Bio:

Fabian co-founded the [UX Camp Hamburg](http://uxcamphh.org) and developed [Github from Scratch](https://opentechschool.github.io/github-from-scratch/) for the Open Tech School. He likes doing sketchnotes and [posting them to flickr](https://www.flickr.com/photos/filtercake) or [writes a blogpost](http://filtercake.com/paper-prototypes-1/) now and then. Currently he does UX Design and UI Development at [Jimdo](http://www.jimdo.com), and yes, Fabian Fabian is actually his real name – he has fonney parents.
##### Photo:

![image](https://cloud.githubusercontent.com/assets/170145/6661143/822d2db0-cba7-11e4-9c53-a1b40e218a89.png)

Photo by [Chris Zielecki](https://www.flickr.com/photos/zanthia)

**Comment by elyseholladay** [comment]
Hi Fabian!

Thank you so much for submitting to SassConf this year!

Unfortunately, we weren’t able to select your talk. 

We had an incredible number of submissions this year: 81, in fact, enough to fill up over two weeks of Sassy goodness! But we only have two days, and we couldn’t pick everything.

If you have any questions at all about our selection process, your submission, or anything else at all, please reach out: elyse@sassconf.com and I’ll gladly give you more details.

Again, thank you for submitting. It’s people like you, who are willing to put themselves out there and work hard and submit and give talks that make it possible to even have SassConf. I hope you will submit again next year and continue to be part of the Sass community!

See you in November!
