### ISSUE TITLE
Sass: The gateway drug for designers who want to code

### ISSUE THREAD

**Issue by adekunleoduye** [SassConf/2015-austin-speaker-cfp#16]
# Sass: The gateway drug for designers who want to code
## Type of Presentation

[ X ] Standard Length Talk
[ X ] Lightning Talk
[  ] Workshop
[  ] Moderated Discussion
## Description

Today a lot of designers are learning how to code to understand the medium they work with. Some just learn the basics of HTML and CSS, but some (like me) get addicted and go a little further.

This addiction isn’t a bad thing. Using technologies like Sass & JS is a great way for designers to validate their user experience and interaction design solutions. Designing a product is more than how it looks --it’s how it functions when users interact with it. The like tools like Sass and JS, make it easier for designer to prototype with real data and have an application that can be tested with real users.

Early in my career, before I knew how to code, I was creating a lot of mockups that I would spent months on and then pass to the developer. But I felt something was missing within this design process. Not until I learned how to code….and to do it quickly, was I able to see a the deficiencies in the UX and interaction design of a product. 

After spending years designing sites and applications with static design comps, I felt that this process made sites stagnant and unintuitive. I realized after I learned Sass and lately Javascript, I became addicted because it gave me the power to design and test out my solutions and gave me the experience to communicate with the developers that would build my design.

The audience will learn:
- How Sass + JS can be used to test UX & Interaction design solutions
- How learning Sass + JS improve process and relationship with developers
- How it can speed up the the feedback process with product owners, stakeholders and clients
## Speaker Info
- Name      : Adekunle Oduye
- Location  : New York, NY
- Contact   : adekunleoduye@gmail.com
##### Social Media:
- Twitter   : [@adekunleoduye](https://twitter.com/adekunleoduye)
- GitHub    : [@adekunleoduye](https://github.com/adekunleoduye)
- Url(s)    : [adekunleoduye.com](http://www.adekunleoduye.com/)
##### Bio:

Adekunle Oduye is a Product Designer at Nasdaq OMX, where he’s part of 30 person team designing web-based products that serve communications, public relations, and investor relations professionals. Adekunle main skillset includes interaction/user interface design and front-end development….which makes him the ultimate weapon! Outside of Nasdaq, Adekunle is a co-organizer for SassConf and Gotham SassMeetup. And when he isn’t working on side projects, he likes to do abstract painting and travel the world….and sometimes jump out of planes!
##### Photo:

![Avatar](https://pbs.twimg.com/profile_images/1879293316/6Rz5Yr7i_400x400)

**Comment by scottkellum** [comment]
I think this is really good and I certainly connect with this. While I knew how to code CSS and HTML, Sass was my gateway drug to programming. I can see this as being more of a hype piece to get the audience pumped about Sass evangelism and education as opposed to a technical focused talk.

**Comment by adekunleoduye** [comment]
@scottkellum what can I improve on to make it more of a technical talk?

**Comment by elyseholladay** [comment]
@adekunleoduye I actually think I'd like to see it as more of an evangelism piece than a technical one. There's so much to cover in terms of technical things (how to do interaction JS, how to do testing, etc, etc) that I fear you might not cover much in 15minutes. But it would be a great way to talk about how to get designers on your team learning/teach them Sass, how to communicate about UI/front-end things, etc.

**Comment by adekunleoduye** [comment]
thanks @elyseholladay & @scottkellum for the feedback! 

That actually scopes the talk a bit. I'm going to make edits to my proposal based on the feedback.

**Comment by elyseholladay** [comment]
Awesome @adekunleoduye! If you want to sign up for office hours and chat with a mentor about how to update it, we'd love it! https://docs.google.com/forms/d/1Goc82y1GE0lh_4Pgr0XaYnuIOBWRNPUw9qikWJihTJk/viewform

**Comment by scottkellum** [comment]
:+1: If you don’t feel comfortable or excited about the advice we are giving, let us know. We’re here to help you pitch the best talk you _want_ to give, not here to tell you what to talk about.

**Comment by adekunleoduye** [comment]
@elyseholladay just signed up..thanks!

@scottkellum I feel comfortable with the advice...this proposal has went through so many changes (all good) base on people thoughts. Since this will be my first time speaking at a conference...I like to keep an open mind.

**Comment by elyseholladay** [comment]
Hi Adekunle!

Thank you so much for submitting to SassConf this year!

Unfortunately, we weren’t able to select your talk. 

We had an incredible number of submissions this year: 81, in fact, enough to fill up over two weeks of Sassy goodness! But we only have two days, and we couldn’t pick everything.

If you have any questions at all about our selection process, your submission, or anything else at all, please reach out: elyse@sassconf.com and I’ll gladly give you more details.

Again, thank you for submitting. It’s people like you, who are willing to put themselves out there and work hard and submit and give talks that make it possible to even have SassConf. I hope you will submit again next year and continue to be part of the Sass community!

See you in November!
