### ISSUE TITLE
The State of Coding on YouTube

### ISSUE THREAD

**Issue by travisneilson** [SassConf/2015-austin-speaker-cfp#22]
# The State of Coding on YouTube
## Type of Presentation

[ x ] Standard Length Talk
or
[ x ] Lightning Talk
[  ] Workshop
[  ] Moderated Discussion
### The state of coding on YouTube

It’s been said more than once that you can learn anything on YouTube. This is especially true of technical web skills.

~Poll audience: how many of you have watched a coding tutorial on YouTube?~

I’d like to talk about the state of coding in online video, and where I think it’s going.
#### What are the options for self learners online?
- blogs
- podcasts
- inspect element
- interactive lessons
- paid video courses
- free video content

I am a YouTuber, I make videos about creating websites and the creative lifestyle. I post a new video every Monday on YouTube the videos range from a 5 minute tip to a 2 hour marathon. I’d like to focus on YouTube, my home.
#### What is a Web Dev YouTuber?

*\* Profile a few Developers.**
- Name / Channel Name
- Reach
- Frequency
- Topics (I can spend a bit of time showcasing sass-specific things if it helps :)
- Play a snippet
- Motivation
- Outcomes

**Devs to Profle**

![Devs to Profile](https://s3.amazonaws.com/f.cl.ly/items/0H3D2a1O2c2G18214647/devs.jpg)
#### Learning at scale

Learning on Youtube is big. Here are some statistics to help you understand just how big:

~Stats~

In the last 365 days there have been **19.1 Billion** views of educational content. **78.1 Million** of those views were in the category of Web Development and Design.

In 2012 the Bureau of Labor Statistics reported that there are 260 Thousand Designers working in the U.S. Now, that’s print designers as well as web, and I’m sure those numbers have changed over the last 3 years. But we can still see that there are about 300 times the views of web design and development as there are workers. 300 times.

I’m sure you all have seen a video or two, maybe casually, maybe you are regular consumers of dev videos. But there are people out there (and I’ve met them) that are marathoning this stuff like it was House of Cards on Netflix.

My channel is one of the smaller ones and the content that I’ve created has been watched for 4.7 Million minutes. That’s equal to **9 years of non-stop playback**.

All of that is to say: Educational content, specifically Web Dev content online, is alive and well.
#### Community

YouTube comments are infamous. Flame wars and hate speak abound. Yet we see something incredible on these specific channels. At the heart of the Dev YouTube experience is a community of extremely helpful and gracious people. People asking valid questions and getting helpful responses. Sharing resources and tips in the comments is the norm.

Now, over on reddit, It’s been said that I have a punchable face (I up-voted that one.) ~screenshot~ But here on YouTube, it’s mostly rainbows.

Why is that?
#### Attitude of giving. An emotional and connective medium.

When you watch a video, you get so much more than a tutorial. You get to know the person behind it. The person who is spending their nights and weekends for your direct benefit. You can’t help but have and intense emotional connection with these YouTubers over time.

Some of these fans are intensely passionate. They wait for the videos with bated breath. Remember that these are people from all walks of life. Some professionals, some aspiring, some hobbyists. All of them here, together, learning, sharing, supporting and encouraging each other.
#### Patreon

My own channel has grown incredibly well over the past year, we have just recently grown off of YouTube. We have a slack organization. A private Podcast. Group hangouts. A Newsletter. Mentoring sessions, and more.

The DevTippers on slack have built side projects together and are now all collaborating on a community project. I won’t give away their ip, but imagine a really snarky twitter bot that reminds you of your todo’s, and keeps you on task.
#### Conclusion

The relationships that these people create will last a lot longer than the videos that I make. These are good people and their connections are strong.

If it’s true that the most valuable thing that we can get from our time online are personal connections, personal relationships. (And I believe it is.) Then YouTube is a place where web developers can find an abundance.

I invite you to take part in this conversation. Learn something. Say hello in the comments. Make some videos of your own.

Be amazed.

Thank you.
## Speaker Info
- Name      : Travis Neilson
- Location  : San Francisco, CA
- Contact   : travisneilson@gmail.com
##### Social Media:
- Twitter   : [@travisneilson](https://twitter.com/travisneilson)
- Twitter   : [@DevTipsShow](https://twitter.com/devtipsshow)
- GitHub    : [DevTips Github](https://github.com/DevTips)
- Url(s)    : [DevTips YouTube Channel](https://www.youtube.com/user/DevTipsForDesigners)
##### Bio:

I’m just trying to make something great before I die. Currently that means I produce YouTube videos on the topic of Web Development and the creative lifestyle.
##### Photo:

![Avatar](https://pbs.twimg.com/profile_images/378800000534594497/ff6e59ec85e5f439931a13a11e7e5212.jpeg)

**Comment by elyseholladay** [comment]
Hi Travis!

Thank you so much for submitting to SassConf this year!

Unfortunately, we weren’t able to select your talk. 

We had an incredible number of submissions this year: 81, in fact, enough to fill up over two weeks of Sassy goodness! But we only have two days, and we couldn’t pick everything.

If you have any questions at all about our selection process, your submission, or anything else at all, please reach out: elyse@sassconf.com and I’ll gladly give you more details.

Again, thank you for submitting. It’s people like you, who are willing to put themselves out there and work hard and submit and give talks that make it possible to even have SassConf. I hope you will submit again next year and continue to be part of the Sass community!

See you in November!
