### ISSUE TITLE
If You Find Yourself Repeating: Pause. Map it. Keep It Movin'

### ISSUE THREAD

**Issue by leng-yang** [SassConf/2015-austin-speaker-cfp#23]
# Title of Presentation (required)

If You Find Yourself Repeating: Pause. Map it. Keep It Movin'
## Type of Presentation (required)

[  ] Standard Length Talk
[ x ] Lightning Talk
[  ] Workshop
[  ] Moderated Discussion
## Description

At some point, we've all repeated our styles in order for us to have multiple options of the same button or link. Simply replacing colors or backgrounds to provide us with 'options' or 'slight contextual variations', as they call it, of the same button but different theme. How about writing and repeating @font-face for whenever we want to bring in a new font for the _nth_ time? Well, thank goodness for Sass Maps!

Maps were release in version 3.3 and are comparative to a Javascript object in that they have key value pairs. With the usage of mixins, placeholders, and extends, one can manipulate your Sass to output all of those pesky class options! No more typing it repetitively (WET) and keeping your Sass DRY and maintainable.

Pros: 
- Options galore
- Minimize files where you need to make changes
- Easily Maintained

Cons:
- Output CSS class selectors that may not always be used
- May irk those who are OCD of their CSS
## Speaker Info (required)
- Name      : Yee Yang
- Location  : Atlanta, GA
- Contact   : yee@ninjapowa.com
##### Social Media:
- Twitter   : [@_yeeyang](https://twitter.com/_yeeyang)
- GitHub    : [yeeyang](https://github.com/yeeyang)
- Url(s)    : [ninjapowa.com](http://ninjapowa.com)
##### Bio:

I'm a front-end developer who dabbles in fresh water aquarium plants, aquaponics, vermiculture, and cooking (italian is my favorite). I've got three kids who keep me pretty busy through out the weekend and my lovely wife who puts that twinkle in my eye. Very serious person. j/k
##### Photo:

![yeeyang_headshot_med](https://cloud.githubusercontent.com/assets/1013506/7288237/91b440be-e92c-11e4-93c5-c794dfc2b0ca.jpg)

**Comment by elyseholladay** [comment]
Hi Yee!

Thank you so much for submitting to SassConf this year!

Unfortunately, we weren’t able to select your talk. 

We had an incredible number of submissions this year: 81, in fact, enough to fill up over two weeks of Sassy goodness! But we only have two days, and we couldn’t pick everything.

If you have any questions at all about our selection process, your submission, or anything else at all, please reach out: elyse@sassconf.com and I’ll gladly give you more details.

Again, thank you for submitting. It’s people like you, who are willing to put themselves out there and work hard and submit and give talks that make it possible to even have SassConf. I hope you will submit again next year and continue to be part of the Sass community!

See you in November!
