### ISSUE TITLE
Sass: The learning bridge between HTML/CSS and JavaScript

### ISSUE THREAD

**Issue by jen4web** [SassConf/2015-austin-speaker-cfp#24]
# Title of Presentation (required)
## Type of Presentation (required)

[ x ] Standard Length Talk
[ x ] Lightning Talk
[  ] Workshop
[  ] Moderated Discussion

Could be either a standard length or lightning talk.
## Description (required)

Many design students new to the programming world enter by learning HTML and CSS. As they make a leap to their first programming language, such as JavaScript, or a library like jQuery, many encounter difficulties, and some drop out of the web world entirely. Teaching resources for JavaScript aren’t necessarily presented with designers in mind — they are created for those who have a programming mindset, or they already know a programming language.

Sass, the CSS preprocessor, features data structures like if/else, loops, variables, and functions. Sass can be written in SCSS format, where the syntax is like CSS, but it must be compiled before sending to the browser. By introducing students to common data structures through Sass, the leap from Sass to JavaScript or jQuery is much smaller and smoother.

In this talk, Jen Kramer proposes a curriculum for easing design students gently into learning JavaScript or jQuery, or any other programming language of interest, by introducing data structures in Sass first.
## Speaker Info (required)
- Name      : Jen Kramer
- Location  : Arlington, MA
- Contact   : jen@jenkramer.org
##### Social Media:
- Twitter   : [@jen4web](url to twitter account)
- GitHub    : [jen4web](url to GitHub account)
- Url(s)    : [jenkramer.org](url to relevant sites)
##### Bio:

For more than a dozen years, Jen Kramer has been educating clients, colleagues, friends and graduate students about the meaning of a "quality website." Since 2000, she has built websites that are supportive of business and marketing goals in a freelance capacity and as part of an agency.

Jen is a lynda.com author with 24 published titles, including the popular "Up & Running with Bootstrap 3", "Joomla 3 Essential Training", and "Web Semantics". Seven of these courses were retired in March 2015.

Jen has written two books published by Wrox Press (a division of Wiley), "Joomla! Start to Finish: How to Plan, Execute, and Maintain Your Web Site" and "Joomla 24-Hour Trainer."

Jen currently offers in-person and online courses through Harvard Extension School and National University. She is also available for individual private tutoring, customized classroom training, and consulting.

Jen earned a BS in biology at University of North Carolina at Chapel Hill and an MS in Internet Strategy Management at the Marlboro College Graduate School.
##### Photo:

![Avatar](http://jenkramer.org/img/jen350high.jpg)

_http://jenkramer.org/img/jen350high.jpg_

**Comment by elyseholladay** [comment]
This looks great! @jen4web do you have any examples of the code you'd show?

**Comment by jen4web** [comment]
Yes, there would be code examples. They will be little snips of things, illustrating how you can teach data structures with Sass.

**Comment by elyseholladay** [comment]
Hi Jen!

Thank you so much for submitting to SassConf this year!

Unfortunately, we weren’t able to select your talk. 

We had an incredible number of submissions this year: 81, in fact, enough to fill up over two weeks of Sassy goodness! But we only have two days, and we couldn’t pick everything.

If you have any questions at all about our selection process, your submission, or anything else at all, please reach out: elyse@sassconf.com and I’ll gladly give you more details.

Again, thank you for submitting. It’s people like you, who are willing to put themselves out there and work hard and submit and give talks that make it possible to even have SassConf. I hope you will submit again next year and continue to be part of the Sass community!

See you in November!
