### ISSUE TITLE
Workshop: What a mess! A workshop on refactoring.

### ISSUE THREAD

**Issue by scottdavis** [SassConf/2015-austin-speaker-cfp#25]
# What a mess! A workshop on refactoring.
## Type of Presentation

[X] Workshop
## Description

Refactoring is hard! But, it can be productive.

Over the years working on Compass and various Sass related projects we have seen some pretty gross code. We will walk through some simple and complex refactorings to help improve the development cycle of your Sass projects.
### Goals

We will learn:
- What [DRY](http://www.google.com/url?q=http%3A%2F%2Fen.wikipedia.org%2Fwiki%2FDon%2527t_repeat_yourself&sa=D&sntz=1&usg=AFQjCNFxueVSOPxh-X_l8m6YI1yKU28k0Q) means.
- Understand [SRP](http://www.google.com/url?q=http%3A%2F%2Fen.wikipedia.org%2Fwiki%2FSingle_responsibility_principle&sa=D&sntz=1&usg=AFQjCNGZvCJ-2Yyosthn0ssTER_8D0eLGw), [SoC](http://www.google.com/url?q=http%3A%2F%2Fen.wikipedia.org%2Fwiki%2FSeparation_of_concerns&sa=D&sntz=1&usg=AFQjCNF1S6YapxEyjYwmlEm-1eJsOIxrng)
- How to use the power of `@functions`.
- Leverage core sass functionality to create declarative abstractions. (Maps, Lists, `@content`, `@mixins`, keyword arguments)
- Organization basics.

What we will do:
- Help people improve their code.
- Teach basic refactoring principals.
- How to unit test sass and regression management.

What we will not do:
- Write code from scratch.
### Workshop lead
- Name      : Scott Davis
- Location  : Taneytown, MD
- Contact   : me@sdavis.info
##### Social Media:
- Twitter   : [@jetviper21](http://twitter.com/jetviper21)
- GitHub    : [scottdavis](http://github.com/scottdavis)
- Url(s)    : [sdavis.info](http://sdavis.info)
##### Bio:

I am the Software Architect at Tourbuzz, Farmer, and Compass/Eyeglass core team member. I have been writing software for 15 years. In my free time I enjoy working on Sass/Compass, studying algorithms and robotics.
##### Photo:

![Photo](http://i.imgur.com/yUIBVvL.jpg)
### Mentor
- Name : Eric Suzanne
- Location  : Denver, CO
- Contact   : eric@oddbird.net
##### Social Media:
- Twitter   : [@ericmsuzanne](http://twitter.com/ericmsuzanne)
- GitHub    : [ericam](http://github.com/ericam)
- Url(s)    : [oddbird.net](http://oddbird.net), [ericsuzanne.com](http://ericsuzanne.com)
##### Bio:

Eric M Suzanne creates web software with OddBird, soundscapes with Teacup Gorilla, wordscapes with [WriteyWrite], and performances with Vicious Trap or the Denver Poetsâ€™ Theatre. Eric is the author of Riding SideSaddle\* and The Post-Obsolete Book, an avid open-source contributor, co-organizer of SassHack Denver, core developer on Compass, and creator of Susy and True.
##### Photo:

![Photo](http://i.imgur.com/abOMeS4.jpg)
### Mentor
- Name : Aaron Gray
- Location  : Boulder & Denver, CO
##### Social Media:
- Twitter   : [@aaronagray](http://twitter.com/aaronagray)
- GitHub    : [aaronagray](http://github.com/aaronagray)
- Url(s)    : [hellometa.com](http://hellometa.com)
##### Bio:

Aaron teaches full-stack, frontend engineering in Galvanize's six month, immersive curriculum, co-authors Beginning Meteor for Apress, is a core developer on Susy, and co-organizes Sass Hack Denver.
##### Photo:

![Photo](http://hellometa.com/public/images/headshot.jpg)
### Mentor
- Name : Jina
- Location  : San Francisco, CA
- Contact   : jina@sushiandrobots.com
##### Social Media:
- Twitter   : [@jina](http://twitter.com/jina)
- GitHub    : [jina](http://github.com/jina)
- Url(s)    : [jina.me](http://jina.me/)
##### Bio:

Jina is a designer, developer, and artist living in San Francisco. She enjoys creating beautiful user experiences. Jina works at Salesforce, originally as a Product Designer for two years with Do (RIP) and now as a Senior Product Designer with the Salesforce UX team. Previously, she has worked at rad companies including Apple, Engine Yard, and Crush + Lovely. She also coauthored two books, Fancy Form Design and The Art & Science of CSS. She has a Bachelor of Fine Arts from Memphis College of Art and is slowly working on receiving her Master of Fine Arts from Academy of Art University.
Jina loves Sass. She leads Team Sass Design, an open source task force that redesigned the Sass brand and website. She organizes the San Francisco Sass meet up, The Mixin. She was a Technical Editor for the book, Sass for Web Designers, by Dan Cederholm (A Book Apart). She is helping Susy, a layout toolkit for Sass. She also created the official Sass port of the responsive design framework, 320 & Up.
##### Photo:

![Photo](http://jina.me/assets/img/jina-e14b3f18.jpg)

Here is a link the the living document: https://docs.google.com/document/d/1bwmk7FOnIQU0LEnzbExm4g4wQOCmlc_nE4dSc7s-58M/edit?usp=sharing

**Comment by elyseholladay** [comment]
Hi Scott (and crew)!

Thank you so much for submitting to SassConf this year!

Unfortunately, we weren’t able to select your workshop. 

We had an incredible number of submissions this year: 81, in fact, enough to fill up over two weeks of Sassy goodness! But we only have two days, and we couldn’t pick everything.

If you have any questions at all about our selection process, your submission, or anything else at all, please reach out: elyse@sassconf.com and I’ll gladly give you more details.

Again, thank you for submitting. It’s people like you, who are willing to put themselves out there and work hard and submit and give talks that make it possible to even have SassConf. I hope you will submit again next year and continue to be part of the Sass community!

See you in November!
