### ISSUE TITLE
Fight the Zombie Pattern Library

### ISSUE THREAD

**Issue by marcelosomers** [SassConf/2015-austin-speaker-cfp#28]
# Fight the Zombie Pattern Library
## Type of Presentation

Standard Length Talk
## Description

In "Fight the Zombie Pattern Library", we'll look at the repeatable processes that Slalom Consulting in Dallas, TX is using to "build a tiny Bootstrap" for every client and keep developers using them every day - processes you can take back and implement tomorrow. 

We'll cover topics such as:
- A scalable process for your designers and developers to maintain a _living_ style guide
- How to generate the information you need for a pattern library, especially if being handed designs to work with
- Usability tips to keep your library easily consumable by developers
- How to add a pattern library in an existing project
- Tools to rapidly spin up libraries if you're in a consulting/agency environment
## Speaker Info (required)
- Name      : Marcelo Somers
- Location  : Flower Mound, TX
- Contact   : msomers at gmail dot com
##### Social Media:
- Twitter   : [@marcelosomers](http://twitter.com/marcelosomers)
- GitHub    : [marcelosomers](https://github.com/marcelosomers)
- Url(s)    : [marcelosomers.com](http://marcelosomers.com)
##### Bio:

Marcelo Somers is a Designer and Front-End Developer at Slalom Consulting where he helps clients solve their biggest challenges through better technology products. Marcelo is passionate about helping teams work better, especially with a focus on the transition between design and development.

In 2011 he founded The Syndicate, a blog sponsorship network that featured writers such as Marco Arment, Khoi Vinh, and David Sparks. It was later sold to BuySellAds. Marcelo has spoken at the Big Design Conference and is a regular guest lecturer at the University of Texas at Dallas.
##### Photo:

![Marcelo Somers](http://marcelosomers.com/dropbox/avatar_2014.jpg)

_http://marcelosomers.com/dropbox/avatar_2014.jpg_

**Comment by misscs** [comment]
Do you use the same tech stack for each client's style guide or does it vary depending on the needs?From your proposal, it sounds like things are rather agnostic.

**Comment by marcelosomers** [comment]
@misscs Great question! At my firm we use several tech stacks (Node, Java, .NET, Angular, etc.), and one of our guiding principles around pattern libraries was that it be platform agnostic (or at least have minimal dependencies) and be something that pushes developers to do the right thing.

This talk really focuses around the _process_ of integrating pattern libraries into your workflow (i.e., how should designers and developers interact, how do you keep developers from straying from the library, etc.) as well as ideas on tools that might help you accomplish that without being overly prescriptive.

**Comment by elyseholladay** [comment]
Hi Marcelo!

Thank you so much for submitting to SassConf this year!

Unfortunately, we weren’t able to select your talk. 

We had an incredible number of submissions this year: 81, in fact, enough to fill up over two weeks of Sassy goodness! But we only have two days, and we couldn’t pick everything.

If you have any questions at all about our selection process, your submission, or anything else at all, please reach out: elyse@sassconf.com and I’ll gladly give you more details.

Again, thank you for submitting. It’s people like you, who are willing to put themselves out there and work hard and submit and give talks that make it possible to even have SassConf. I hope you will submit again next year and continue to be part of the Sass community!

See you in November!
