### ISSUE TITLE
From CSS to Sassy Bootstrap...

### ISSUE THREAD

**Issue by al-the-x** [SassConf/2015-austin-speaker-cfp#31]
# From CSS to Sassy Bootstrap...
## Description

Are you stuck in CSS? Maybe you're married to Bootstrap and all that `<div>` soup and just can't see a way out. You know that your styles would be so much easier to maintain if you couls just make the jump to Sass, but... Look, it's complicated.

Fear not, faithful steward of the internet. Professional refactoring is a delicate and arcane art that involves making changes that are invisible from the outside, but any decent developer can learn the technique.

In this 4 hour tutorial, [David Rogers](http://al-the-x.me), Front-End Instructor at [The Iron Yard](http://theironyard.com) in Orlando, FL, will take you through a heavy refactor of a decently complex CSS layout to full Sass... without breaking anything. With the help of some brave audience volunteers, David will apply the same principles and experience to one of _your_ projects. Finally, he'll refactor some messy Bootstrap markup into clean, semantic Sassy Bootstrap.
#### Agenda
- **Principles of Refactoring CSS (slides)** (~30m)
  - What is Refactoring? -- definition and exposition
  - Okay, gimme some examples...
    - Add whitespace to improve readability
    - De-duplicate styles with compound selector
    - Move repetitive styles into shared selector
  - Pain points with CSS
    - Unnecessary duplication of selectors
    - Limitations of native constructs: `@import`
    - Cascade and specificity FAIL
    - Complex (but semantic!) selector FAIL
  - The Sassing of the CSS
    - Basic Syntax: 
      - It's also just CSS!
      - Nesting selectors is easy...
        - What does _that_ do? (Compiled Output)
        - Get your `:hover` states! (Parent Selector)
      - Variables on the money...
        - Name your own damn colors!
        - But that's not all...!
      - Math is fun again!
        - Why calculate those percentages yourself?
        - Why not add up some colors?
      - See what I'm getting `@`...?
        - Just `@import` it anywhere...
        - Easier `@media` queries...
        - Start `@mixin` it up...
        - `@extend` your reach...
  - Take a breath... (5m break)
- **Walkthrough: CSS to Sass, Part 1** (~30m)
  - Some Brief Yak Shaving
    - You will need: 1 Sass compiler
      - A word about `node-sass`...
      - And good ole `ruby-sass`...
      - Don't look now, here comes Compass!
    - Build processes aren't that hard, really.
      - Don't fear the command line.
      - But you _can_ just use a GUI, too.
  - First you get the CSS and you mash it, mash it...
    - Start with [some reasonably complex CSS](http://tympanus.net/codrops/2013/03/29/nested-accordion/)...
    - Convert the file extension from `.css` to `.scss`
    - Apply your Sass implementation of choice:
    - Save the results: voila!
  - I was promised a good refactoring...
    - Reduce duplication of selectors with _nesting_...
    - Reduce duplication of _properties_ with nesting...?
    - Cover that `:hover` with `&`...
    - Recompile and reload!
- **Intermission and Q&A** (~10m)
- **Walkthrough: CSS to Sass, Part 2** (~30m)
  - Start with [a more complex example](http://tympanus.net/codrops/2013/07/01/view-mode-switch/)
  - Refactor to nested selectors
  - Maybe [one more example](http://tympanus.net/codrops/2013/05/17/product-grid-layout/)? (time permitting)
- **Intermission** (~15m)
  - Soliciting examples from the audience?
- **Walkthrough: Bootstrap to Sassy Bootstrap, Part 1** (~30m)
  - Yak Shaving: Getting Bootstrap to play nice with Sass
  - Refactor: Example with Bootstrap grid classes
  - Refactor: Example with Bootstrap components
- **Intermission and Q&A** (~10m)
- **Walkthrough: Bootstrap to Sassy Bootstrap, Part 2** (~30m)
  - Unfortunate side-effects...
    - Look at all that CSS!
    - Trimming the fat with `%`...
  - Alternatives to Bootstrap that play nicer:
    - [Bourbon](http://bourbon.io) and [Neat](http://neat.bourbon.io)
    - [Susy](http://susy.oddbird.net/) (but `ruby-sass` only :disappointed:)
  - Let's work on something together!
- **Wrap-up and Q&A** (~20m)
### Workshops: Coding Exercise (required for workshops only)

Attendees should have code editor -- Sublime Text, Atom, Brackets, etc -- installed and configured. Existing knowledge of CSS syntax, selectors, and properties is required. No previous experience with Sass is required but familiarity with the grid and components provided by Bootstrap is expected.

Attendees will work through refactoring some canned examples of moderately complex CSS into clearer, cleaner Sass with follow-along directions. At the middle intermission, examples of projects for refactoring will be solicited from the audience for use in the final segment. If time allows, the group will build a reasonably complex layout with the Bootstrap grid and components _without using a single Bootstrap class_. All exercises will be instructor-led and interactive.
## Speaker Info
- Name      : David Rogers
- Location  : Orlando, FL
- Contact   : hello@al-the-x.me
##### Social Media:
- Twitter   : [@al_the_x](https://twitter.com/al_the_x)
- GitHub    : [al-the-x](https://github.com/al-the-x)
- Url(s)    : [About.me](http://about.me/al_the_x), [everything](http://j.mp/al_the_x)
##### Bio:

David Rogers wrangles @orlandophp & @orlandopython, teaches JavaScript for @TheIronYard, runs @JEAcademy, hacks freelance, and gots kids.

> I help build the internet everyday using the power of my mind, a lot of typing, and copious handshakes and conversations. Swearing occasionally helps. I help organize nerds, run community events, and teach people. Sometimes I make money while doing it. Sometimes.
##### Photo:

![Avatar (HIRES)](https://cloud.githubusercontent.com/assets/96015/8022480/a22a41fc-0ca2-11e5-9f90-885f793b71a6.png)
![Photo](https://www.dropbox.com/sc/qe5dfs7b3zxmwgo/AAB0s1Ih8HjmOWKhcE1QlVo-a/0?dl=1)

**Comment by misscs** [comment]
Hi, @al-the-x, thanks for submitting. Is this workshop assuming that attendees have a basic knowledge of Sass or will you be covering Sass features/concepts as part of the workshop? Are there coding exercises or sessions built in for attendees to try the concepts you are teaching? 

Just a friendly reminder: don't forget to update the rest of the template with your details!

**Comment by al-the-x** [comment]
Thanks for the ping @misscs! Yes, the proposed plan is to include enough basic Sass to appeal to beginners, but I don't intend to cover basic CSS. The entire workshop is planned as an extended coding exercise, actually, with plenty of breaks for people to stretch and discuss.

**Comment by elyseholladay** [comment]
Hi David!

Thank you so much for submitting to SassConf this year!

Unfortunately, we weren’t able to select your workshop. 

We had an incredible number of submissions this year: 81, in fact, enough to fill up over two weeks of Sassy goodness! But we only have two days, and we couldn’t pick everything.

If you have any questions at all about our selection process, your submission, or anything else at all, please reach out: elyse@sassconf.com and I’ll gladly give you more details.

Again, thank you for submitting. It’s people like you, who are willing to put themselves out there and work hard and submit and give talks that make it possible to even have SassConf. I hope you will submit again next year and continue to be part of the Sass community!

See you in November!
