### ISSUE TITLE
Maintainable Style Guides

### ISSUE THREAD

**Issue by bpainter** [SassConf/2015-austin-speaker-cfp#32]
# Maintainable Style Guides
## Type of Presentation (required)

[x] Standard Length Talk
[  ] Lightning Talk
[  ] Workshop
[  ] Moderated Discussion
## Description (required)

A style guide is a great collaboration tool to bridge communication gaps between business stakeholders, designers, and developers. Static or living style guides are a great place to start but become increasingly difficult to maintain because style guide generators are dependent on parsing comments in CSS in order to generate HTML patterns and documentation. In short, there is no single source of truth for the HTML leading to maintainability problems. In this session we will discover creating a truly reusable module by creating a pattern API.

Five things audience members will learn:
1. modular template patterns
2. dependency management and versioning per module
3. turning modules into the “single source of truth” through a module API
4. how to call the API to create a style guide
5. how to call the API to create templates and pages within an application

Technologies used:
Node, Angular or React, Component, Sass (Libsass)
## Speaker Info (required)
- Name      : Bermon Painter
- Location  : Charlotte, NC
- Contact   : bermonpainter@gmail.com
##### Social Media:
- Twitter   : [@bermonpainter](http://twitter.com/bermonpainter)
- GitHub    : [bermonpainterl](http://github.com/bpainter)
##### Bio:

A rootbeer drinking, cupcake eating, Spanish speaking, piano playing, handlebar mustache wearing designer/developer hybrid living in the glorious city of Charlotte, NC  Bermon is the organizer of various community groups for user experience designers and front-end developers, and the organizer of Blend Conference, a 3-day multi-track event for user experience strategists, designers, and developers. He also leads the user experience team for Cardinal Solutions' Charlotte office where he consults with large enterprise clients on interesting problems across user experience, design, and front-end development. 
##### Photo:

![Avatar](http://c4.staticflickr.com/4/3877/15126818127_455a11909b_z.jpg)

**Comment by elyseholladay** [comment]
Hi Bermon!

Thank you so much for submitting to SassConf this year!

Unfortunately, we weren’t able to select your talk. 

We had an incredible number of submissions this year: 81, in fact, enough to fill up over two weeks of Sassy goodness! But we only have two days, and we couldn’t pick everything.

If you have any questions at all about our selection process, your submission, or anything else at all, please reach out: elyse@sassconf.com and I’ll gladly give you more details.

Again, thank you for submitting. It’s people like you, who are willing to put themselves out there and work hard and submit and give talks that make it possible to even have SassConf. I hope you will submit again next year and continue to be part of the Sass community!

See you in November!
