### ISSUE TITLE
Mathemagical Conversations - A Deep Dive on Math and Units in Sass

### ISSUE THREAD

**Issue by bookwyrm** [SassConf/2015-austin-speaker-cfp#33]
# Mathemagical Conversations - A Deep Dive on Math and Units in Sass
## Type of Presentation

[ X ] Standard Length Talk
[ X ] Lightning Talk
[  ] Workshop
[  ] Moderated Discussion
## Description

Sass provides a lot of help with units and math. We will take deep dive to look at unit handling and math functions that can make your life easier.

This could be either a Lightning Talk or a Standard Length Talk - mostly based on how many Use Cases we look at.
### High-level outline
- Computable values
  - Numbers
  - Colors
- Math Operators
- “Math” Functions
  - percentage
  - round
  - ceil
  - green
  - rgba
  - hsla
  - ie-hex-str
- Units
  - List of Units - px, em, rem, vh, vw, vmin, vmax
  - Colors have “units” too (RGBA/HSLA)
  - Comparing colors - need definition based on color wheel
  - When to use them
  - em vs rem
  - conversions
  - considerations for RWD
- Use Cases
  - Grid System
  - Padding on Nested Grid System
  - Creating a Color Palette
  - More to come...
## Speaker Info
- Name      : Matt Vanderpol
- Location  : Nevada City, CA
- Contact   : matt@vanderpol.net
##### Social Media:
- Twitter   : [@bookwyrm](https://twitter.com/bookwyrm)
- GitHub    : [bookwyrm](https://github.com/bookwyrm)
- Url(s)    : [mattvanderpol.com](http://mattvanderpol.com)
##### Bio:

Matt is a full-stack developer consultant who has been happily using Sass for front-end dev for 3 years to make the process of styling web sites and web apps more enjoyable. He has worked on a variety of sites ranging from Silicon Valley tech companies down to local small businesses.

Matt lives in Nevada City, CA in a house that he and his wife [designed and built](http://house.vanderpol.net). When he is not in front of a computer, he enjoys hiking, camping, and backpacking with his family.
##### Photo:

![Matt Vanderpol](http://mattvanderpol.com/bio-photo-500x500.jpg)

**Comment by elyseholladay** [comment]
Hi Matt!

Thank you so much for submitting to SassConf this year!

Unfortunately, we weren’t able to select your talk. 

We had an incredible number of submissions this year: 81, in fact, enough to fill up over two weeks of Sassy goodness! But we only have two days, and we couldn’t pick everything.

If you have any questions at all about our selection process, your submission, or anything else at all, please reach out: elyse@sassconf.com and I’ll gladly give you more details.

Again, thank you for submitting. It’s people like you, who are willing to put themselves out there and work hard and submit and give talks that make it possible to even have SassConf. I hope you will submit again next year and continue to be part of the Sass community!

See you in November!
