### ISSUE TITLE
You're a Front-End Developer, and You Can Make Games, Too!

### ISSUE THREAD

**Issue by aliciasedlock** [SassConf/2015-austin-speaker-cfp#34]
## Type of Presentation

[x] Standard Length Talk
[  ] Lightning Talk
[  ] Workshop
[  ] Moderated Discussion
## Description

I love games. Games can be powerful learning tool. Or just plain old fun. And for a long time I thought making games was a weird mystical skill that I could never obtain. I mean, sure, I’ve made websites and apps for 5+ years, but games? Nah. Never.

Until I tried it. And it was possible! It's no _Assasin's Creed_, but it’s a game! And that’s when I realized that HTML, CSS, and JS have made such large strides in recent years that in-browser game development has one of the lowest barriers to entry.

In this talk I’d like to demo some small prototypes covering game concepts built with front-end tech, how front-end developers can start to make games for themselves using the tools they already know and love, such as:
- CSS animations and transitions, to bring your character to life
- Sass loops and mixins, to add variety to your enemies
- Simple HTML elements like divs and checkboxes, to interact with the game environment

Ideally, this talk would include a few demos that build upon these things. Perhaps starting at a simple game (tic-tac-toe?) and continuing to something more complex (whack a mole? side scroller?)
## Speaker Info
- Name      : Alicia Sedlock
- Location  : Boston, MA
- Contact   : aliciasedlock@gmail.com
##### Social Media:
- Twitter   : [@aliciability](https://twitter.com/aliciability)
- GitHub    : [aliciasedlock](https://github.com/aliciasedlock)
- Url(s)    : [Horse Combat For Horsemanity - My First Game](http://horsemanity.herokuapp.com/)
##### Bio:

Alicia Sedlock is a front-end developer in Boston, MA. When she's not working at Society of Grownups, she's a teacher and organizer for Girl Develop It and a co-organizer of the Purple Monkey Game Jam. Outside of tech, she is constantly switching hobbies. Right now it's brewing hard cider and redecorating her apartment.
##### Photo:

![Avatar](http://aliciasedlock.github.io/images/headshot.jpg)

**Comment by scottkellum** [comment]
I’m really curious about your process here. Game dev sounds like a lot of fun as well as a huge opportunity to learn.

**Comment by aliciasedlock** [comment]
@scottkellum Is that more in terms of the process of coming up with an idea, or the process of actually developing the game? Both would be good to touch on if I could fit it into 40 minutes without rushing through the content.

**Comment by scottkellum** [comment]
both :smile: 

Yeah a ton of good stuff here. I wonder if there is any way to have a simple game that the audience can participate in as well.

**Comment by aliciasedlock** [comment]
I've been trying to actually think of a game that can be played by many people in the same room all at once! I think that would be awesome, but more realistically, I'd at least want 2-3 small games that I can share out, or even put into CodePen, so that folks can check out the code too.

**Comment by scottkellum** [comment]
Nice! You can also sign up for office hours with a mentor if you want to work through any of these ideas with someone: http://sassconf.com/chat/

**Comment by elyseholladay** [comment]
Hi Alicia!

Thank you so much for submitting to SassConf this year!

Unfortunately, we weren’t able to select your talk. 

We had an incredible number of submissions this year: 81, in fact, enough to fill up over two weeks of Sassy goodness! But we only have two days, and we couldn’t pick everything.

If you have any questions at all about our selection process, your submission, or anything else at all, please reach out: elyse@sassconf.com and I’ll gladly give you more details.

Again, thank you for submitting. It’s people like you, who are willing to put themselves out there and work hard and submit and give talks that make it possible to even have SassConf. I hope you will submit again next year and continue to be part of the Sass community!

See you in November!
