### ISSUE TITLE
Sass is Dead; Long Live CSS

### ISSUE THREAD

**Issue by alanmoo** [SassConf/2015-austin-speaker-cfp#35]
# Sass is Dead; Long Live CSS
## Type of Presentation

[x] Standard Length Talk
[  ] Lightning Talk
[  ] Workshop
[  ] Moderated Discussion
## Description (required)

The front end workflow is constantly evolving. In the last few years, preprocessors and build tools have taken the main stage to help us write our code quickly and modularly. There’s no doubt that they’re incredibly helpful today, but are they going to be right for the future of the web? In this talk I’ll discuss possible performance problems with preprocessors through numerical analysis of generated CSS (considering file size when using nesting, extends, and gzip), and look forward to changes in the web that will dramatically reduce our reliance on preprocessors (post-processors, the death of vendor prefixing, CSS variables, HTTP/2, web components, element queries, and more).
## Speaker Info (required)
- Name      : Alan Mooiman
- Location  : Depends on the conference dates. Probably Portland, OR
- Contact   : alan@alanmooiman.com
##### Social Media:
- Twitter   : [@alanmoo](http://twitter.com/alanmoo)
- GitHub    : [alanmoo](http://github.com/alanmoo)
- Url(s)    : [alanmooiman.com](http://alanmooiman.com)
##### Bio:

Alan is a front end developer with a design background and a passion for great interfaces. He's currently in the process of moving from NYC to Portland, OR to explore the west coast. In his free time, he dabbles in iOS development, pokes around in back end code, and builds hot tubs in his back yard.
##### Photo:

![Avatar](http://alanmooiman.com/images/headshot256.png)

**Comment by scottkellum** [comment]
Thanks for submitting! Sounds like this could be an interesting talk. It raises a lot of questions for me though, mostly you are listing future technologies while eluding to an opinion on them and it’s unclear what that opinion is. The shock value is here, I’d like to know a little more about what I should be shocked about.

**Comment by alanmoo** [comment]
I'd like to get people to think about the reason we use Sass- It's partially about things simply CSS can't do due to language constructs, but it also helps us solve problems that future web tech might allow us to solve in a different way. There are also situations where Sass alone can't be the entire solution due to its limitations as a preprocessor. I want to highlight this symbiotic relationship and get people to think about their toolchain.

**Comment by elyseholladay** [comment]
Hi Alan!

Thank you so much for submitting to SassConf this year!

Unfortunately, we weren’t able to select your talk. 

We had an incredible number of submissions this year: 81, in fact, enough to fill up over two weeks of Sassy goodness! But we only have two days, and we couldn’t pick everything.

If you have any questions at all about our selection process, your submission, or anything else at all, please reach out: elyse@sassconf.com and I’ll gladly give you more details.

Again, thank you for submitting. It’s people like you, who are willing to put themselves out there and work hard and submit and give talks that make it possible to even have SassConf. I hope you will submit again next year and continue to be part of the Sass community!

See you in November!
