### ISSUE TITLE
Sass Patterns for Forms

### ISSUE THREAD

**Issue by bookwyrm** [SassConf/2015-austin-speaker-cfp#37]
# Sass Patterns for Forms
## Type of Presentation

[ ] Standard Length Talk
[ X ] Lightning Talk
[  ] Workshop
[  ] Moderated Discussion
## Description

We will look at several topics and patterns in Sass that make it easier to style and maintain different types of forms within a single site or app.

Topics and Patterns will include:
- Intro to BEM
- Form Types (presentation)
- Field Types
- Responsive Treatment
- Accessibility
## Speaker Info
- Name      : Matt Vanderpol
- Location  : Nevada City, CA
- Contact   : matt@vanderpol.net
##### Social Media:
- Twitter   : [@bookwyrm](https://twitter.com/bookwyrm)
- GitHub    : [bookwyrm](https://github.com/bookwyrm)
- Url(s)    : [mattvanderpol.com](http://mattvanderpol.com)
##### Bio:

Matt is a full-stack developer consultant who has been happily using Sass for front-end dev for 3 years to make the process of styling web sites and web apps more enjoyable. He has worked on a variety of sites ranging from Silicon Valley tech companies down to local small businesses.

Matt lives in Nevada City, CA in a house that he and his wife [designed and built](http://house.vanderpol.net). When he is not in front of a computer, he enjoys hiking, camping, and backpacking with his family.
##### Photo:

![Matt Vanderpol](http://mattvanderpol.com/bio-photo-500x500.jpg)

**Comment by elyseholladay** [comment]
Hi Matt!

Thank you so much for submitting to SassConf this year!

Unfortunately, we weren’t able to select your talk. 

We had an incredible number of submissions this year: 81, in fact, enough to fill up over two weeks of Sassy goodness! But we only have two days, and we couldn’t pick everything.

If you have any questions at all about our selection process, your submission, or anything else at all, please reach out: elyse@sassconf.com and I’ll gladly give you more details.

Again, thank you for submitting. It’s people like you, who are willing to put themselves out there and work hard and submit and give talks that make it possible to even have SassConf. I hope you will submit again next year and continue to be part of the Sass community!

See you in November!
