### ISSUE TITLE
Throw-Away Code

### ISSUE THREAD

**Issue by nrrrdcore** [SassConf/2015-austin-speaker-cfp#38]
# Throw-Away Code
## Type of Presentation

[ x ] Standard Length Talk
[  ] Lightning Talk
[  ] Workshop
[  ] Moderated Discussion
## Description (required)

Whether or not your team expects its designers to write production code, there are some huge benefits of having more overlap between your team’s design and development processes. Thinking about design in a modular, object-oriented way can also dramatically improve the experience felt by your end-user.

I’ll take you on a journey with a UX team @ Amazon whose designers had never professionally pushed code, but were experiencing pain from the disconnect between the design and development processes. We’ll explore how teaching them to code, building a designing-in-browser dev environment with Middleman, and creating a resusable pattern library with SASS, OOCSS and BEM conventions allowed our team to smooth out an otherwise bumpy product development cycle.

Other super fun things we’ll discuss working with: “media objects”, partials, plug and play animations, & my fav responsive grid system.
## Speaker Info (required)
- Name      : Julie Ann Horvath 
- Location  : Oakland, CA
- Contact   : jannhorvath@gmail.com
##### Social Media:
- Twitter   : [@nrrrdcore](https://twitter.com/nrrrdcore)
- GitHub    : [@nrrrdcore](https://github.com/nrrrdcore)
- Url(s)    : [hire.julieannhorvath.com](http://hire.julieannhorvath.com/)
##### Bio:

I’m Julie Ann Horvath, _a designer who codes_. With a background in writing, information design is at the heart of everything I build. I’m completely obsessed with CSS, my dog, and painting the perfect lip. 

I’m the creator of tech’s first all-women talk series, Passion Projects. I write things about design and development at [One Neat Trick](https://medium.com/one-neat-trick), a shiny new publication for bite-size tips re: web development and designing-in-browser, and I’m also the curator of [#UXSCHOOL](https://twitter.com/search?q=%23UXSCHOOL&src=typd), a series of tweets about well-designed user-experiences on the Internet. Say hello to me on twitter [@nrrrdcore](https://twitter.com/nrrrdcore).
##### Photo:

![Avatar](https://pbs.twimg.com/profile_images/589622444186468352/pKcp1Bpa.jpg)

**Comment by elyseholladay** [comment]
Hi Julie!

Thank you so much for submitting to SassConf this year!

Unfortunately, we weren’t able to select your talk. 

We had an incredible number of submissions this year: 81, in fact, enough to fill up over two weeks of Sassy goodness! But we only have two days, and we couldn’t pick everything.

If you have any questions at all about our selection process, your submission, or anything else at all, please reach out: elyse@sassconf.com and I’ll gladly give you more details.

Again, thank you for submitting. It’s people like you, who are willing to put themselves out there and work hard and submit and give talks that make it possible to even have SassConf. I hope you will submit again next year and continue to be part of the Sass community!

See you in November!

p.s. Thanks for choosing us to be your first talk submission after such a long break! We were very honored :sparkling_heart:
