### ISSUE TITLE
Get Sass(ed)

### ISSUE THREAD

**Issue by Twintails** [SassConf/2015-austin-speaker-cfp#40]
# Title of Presentation

Get Sass(ed)
## Type of Presentation

Lightning Talk
## Description

Get your team going and integrate Sass into your existing company projects. 

A quick setup to get going on existing older projects. 
Begin refactoring your code into partials. 

Fine Print:
This will likely be a beginner/starter talk
## Speaker Info
- Name      :  Lawrence Francell
- Location  :  Austin, TX
- Contact   : lawrence@twintails.com
##### Bio:

I’m a Lead UX Developer and Experience Advocate for Texas.gov. I am a front end developer and aspiring Node.js developer. I am an artist, sculptor, woodworker, metalworker and all around maker and builder of things.
##### Photo:

![Avatar](http://www.gravatar.com/avatar/5bf6ac5b3b17c5598f20e5ab903c5537.png)

**Comment by elyseholladay** [comment]
Hi Lawrence!

Thank you so much for submitting to SassConf this year!

Unfortunately, we weren’t able to select your talk. 

We had an incredible number of submissions this year: 81, in fact, enough to fill up over two weeks of Sassy goodness! But we only have two days, and we couldn’t pick everything.

If you have any questions at all about our selection process, your submission, or anything else at all, please reach out: elyse@sassconf.com and I’ll gladly give you more details.

Again, thank you for submitting. It’s people like you, who are willing to put themselves out there and work hard and submit and give talks that make it possible to even have SassConf. I hope you will submit again next year and continue to be part of the Sass community!

See you in November!

**Comment by Twintails** [comment]
Thank you for the opportunity! I read trough the "How we selected" and completely understand the criteria and process. Y'all certainly had quite a bit of work to get the selections honed down. 
I'm looking forward to it in November.

**Comment by elyseholladay** [comment]
Thanks for the kind words @Twintails! Appreciate you submitting! We are looking forward to Nov too! :)
