### ISSUE TITLE
Transcending Sass: Tooling for the future

### ISSUE THREAD

**Issue by xzyfer** [SassConf/2015-austin-speaker-cfp#43]
# Static analysis of Sass
## Type of Presentation (required)

[x] Standard Length Talk
[  ] Lightning Talk
[  ] Workshop
[  ] Moderated Discussion
## Description (required)

I imagine a world of incredible powerful Sass tooling, the likes we're used to in JavaScript. A world in the blink of an eye we could:
- lint our Sass
- gather accurate statistics
- transform it on the fly
- even disable language features

This is world I want to live in, I want to talk about how we're getting there.

October 22nd 2012 - although little celebrated - is the day we forever changed how we engineer, author, and distribute our JavaScript. On this day Ariya Hidayat released [Esprima](https://github.com/jquery/esprima) v1.0.0. 

Esprima brought static analysis of JavaScript to the masses for the first time. This meant we could view our code as an object and that object could be manipulated or analysed in any way we desired. Like our prehistoric ancestors discovering fire, the JavaScript community embraced their new powers and the modern age of tooling was born. Almost three years later we have mature tooling ecosystem of
- linters
- minifiers
- optimizers
- bundler
- coverage analysis
- quality analysis
- transpilers

Esprima was a spark that we as a community turned into a revolution. With today's tools we're able to ask just about any question of our JavaScript code, and get an accurate answer -- Esprima made that possible.

Inspired by the success of our scripting brethren. I've started working on a set of low level tools for Sass. Among them is a Sass parser, like Esprima, will give our community a framework that'll allow a deeper level of authoring control. 

I've collaborated with fellow Sasstronauts to build the first consumer of these tools. Sass Lint will be a fast, node based Sass linter.

I will talk about _what_ these tools are and _why_ we need them. I'll address some uses cases, including Sass Lint, and demo the first ever(?) Sass transpiler. Much like it's JavaScript equivalents it will allow the ability to extend the Sass language with experimental new features, or fix some of the language's rough edges.

Thee audience will leave excited, and feeling empowered. They will question their Sass, and know they now have the power to get an accurate answer. Most importantly I want them to dream about what their Sass can be.
## Speaker Info (required)
- Name      : Michael Mifsud
- Location  : Melbourne, Au
- Contact   : xzyfer+sassconf@gmail.com
##### Social Media:
- Twitter   : [@xzyfer](https://twitter.com/xzyfer)
- GitHub    : [xzyfer](https://github.com/xzyfer)
##### Bio:

I'm a full stack engineer at 99designs focusing primarily on frontend and tooling.
An advocate for open source software I'm currently the project lead for [Node Sass](https://github.com/sass/node-sass) and a core contributor to [Libsass](https://github.com/sass/libsass).
I'm also heavily involved in the local developer community as part of the [CSSConf AU](http://cssconf.com.au) and the [MelbCSS meetup](http://www.meetup.com/MelbCSS/) organising teams.
##### Photo:

![michael-m2](https://cloud.githubusercontent.com/assets/579928/7727181/7cc3fc6a-ff4a-11e4-944b-30b96e694744.jpg)

**Comment by elyseholladay** [comment]
Hi Michael!

Thank you so much for submitting to SassConf this year!

Unfortunately, we weren’t able to select your talk. 

We had an incredible number of submissions this year: 81, in fact, enough to fill up over two weeks of Sassy goodness! But we only have two days, and we couldn’t pick everything.

If you have any questions at all about our selection process, your submission, or anything else at all, please reach out: elyse@sassconf.com and I’ll gladly give you more details.

Again, thank you for submitting. It’s people like you, who are willing to put themselves out there and work hard and submit and give talks that make it possible to even have SassConf. I hope you will submit again next year and continue to be part of the Sass community!

See you in November!
