### ISSUE TITLE
Designing Digital Communities

### ISSUE THREAD

**Issue by nathan-hinshaw** [SassConf/2015-austin-speaker-cfp#45]
# Designing Digital Communities
## Type of Presentation (required)

[ X ] Standard Length Talk
[   ] Lightning Talk
[   ] Workshop
[   ] Moderated Discussion
## Description (required)

As the architectural complexities and user expectations of websites continue to evolve, viewing them as the communities that they are–or can become–is increasingly important to both their sustainability and success. How do we as technologists design, build, and maintain these properties; while also evolving the tools we use to support them? 

Some of the topics we'll look at include:
• Streamlining the approach to design patterns, development processes and feedback cycles
• How Threadless has worked to foster collaboration between users and developers by encouraging both active and passive participation
• How to best leverage a community's shared assets, inspiration, and potential, with the intention of creating digital spaces that promote users' sense of inclusion and satisfaction
• Looking at existing real world design patterns (e.g. universal iconography and visual wayfinding) as a means of creating more accessible user experiences in a digital space
• Responsible development: pushing design and technology forward without dragging users behind you
## Speaker Info (required)
- Name      : Nathan Hinshaw
- Location  : Chicago, IL
- Contact   : nathanh@threadless.com
##### Social Media:
- Twitter   : [@nathanhinshaw](https://twitter.com/nathanhinshaw)
- GitHub    : [nathan-hinshaw](https://github.com/nathan-hinshaw)
- Url(s)    : [nathan-hinshaw.com](http://www.nathan-hinshaw.com)
##### Bio:

Nathan Hinshaw is the Lead Front End Engineer and a Product Owner at Threadless, where he brings his passion for data-driven, cross-device development to the best platform for supporting artists worldwide. He believes in writing lean, modular HTML, SCSS, and Javascript while crafting empathetic, intuitive interfaces. When not creating for the web he can be found at his ceramics wheel or scouring cookbooks for a new all day cooking project.
##### Photo:

![My Photo](http://nathan-hinshaw.com/img/nathan-hinshaw.jpg)

**Comment by elyseholladay** [comment]
Hi Nathan!

Thank you so much for submitting to SassConf this year!

Unfortunately, we weren’t able to select your talk. 

We had an incredible number of submissions this year: 81, in fact, enough to fill up over two weeks of Sassy goodness! But we only have two days, and we couldn’t pick everything.

If you have any questions at all about our selection process, your submission, or anything else at all, please reach out: elyse@sassconf.com and I’ll gladly give you more details.

Again, thank you for submitting. It’s people like you, who are willing to put themselves out there and work hard and submit and give talks that make it possible to even have SassConf. I hope you will submit again next year and continue to be part of the Sass community!

See you in November!
