### ISSUE TITLE
Thinking Laterally

### ISSUE THREAD

**Issue by HamptonMakes** [SassConf/2015-austin-speaker-cfp#47]
# Thinking Laterally
## Type of Presentation (required)

[  ] Standard Length Talk
[x] Lightning Talk
[  ] Workshop
[  ] Moderated Discussion
## Description (required)

Our brains are amazing at many things, but they are extremely bad at seeing the often obvious answer to a problem. I believe this occurs because we tend to group-think... the thoughts of how other people view the world cement in our minds and become the way we see things. Often times, there are obvious answers to many problems and we simply don't see them. I believe it's not because we aren't smart, but because we easily fall into the same thought patterns as everyone else around us.

As technologists and creators, our job is to see around the corner of the future. To come up with solutions and answers that are unique and make the world just a little tiny bit better. We need to harness and grow our skepticism of what we've been told to assume and don't believe everything that people have told us.

For me, I credit my ability to think laterally with growing up gay in the deep south. Everyone around me believed that being gay was sinful and evil, but inside me I felt fine and the crush I had on the guys at school only felt good and okay to me. This dissonance between what I felt and observed and what the world around me said was the truth pushed me to have to reject the assumptions around me and go find my own truth.

To think laterally doesn't require growing up in a sexual minority, but it requires rejecting the idea that someone else always knows better. It requires trust in yourself and your mind and your heart. Following those things is thinking laterally and I'd love the opportunity to share these feelings and ideas with the awesome Sass community.
## Speaker Info (required)
- Name      : Hampton Catlin
- Location  : San Francisco, CA
- Contact   : hcatlin@gmail.com
##### Social Media:
- Twitter   : @hcatlin
- GitHub    : hcatlin
- Url(s)    : http://www.hamptoncatlin.com http://www.wordset.org
##### Bio:

Inventor of Sass, Haml, and Wikipedia Mobile. Co-founder of Wordset, where we're revolutionizing language and collaboration models. Co-host of the podcast, We Have A Microphone. Developer, Speaker, Creator, Humanist, Futurist, Doing My Best.
##### Photo:

![196323_435937593144656_980924109_n](https://cloud.githubusercontent.com/assets/111/7692055/c92f10b2-fd74-11e4-96fc-182c073a7fe7.jpg)

**Comment by elyseholladay** [comment]
Hi Hampton!

Thank you so much for submitting to SassConf this year!

Unfortunately, we weren’t able to select your talk. 

We had an incredible number of submissions this year: 81, in fact, enough to fill up over two weeks of Sassy goodness! But we only have two days, and we couldn’t pick everything.

If you have any questions at all about our selection process, your submission, or anything else at all, please reach out: elyse@sassconf.com and I’ll gladly give you more details.

Again, thank you for submitting. It’s people like you, who are willing to put themselves out there and work hard and submit and give talks that make it possible to even have SassConf. I hope you will submit again next year and continue to be part of the Sass community! (You will, right? :stuck_out_tongue: )

See you in November!
