### ISSUE TITLE
4 years of open source and inspiration

### ISSUE THREAD

**Issue by scottkellum** [SassConf/2015-austin-speaker-cfp#5]
#4 years of open source and inspiration
## Type of Presentation
- [x] Standard Length Talk
- [x] Lightning Talk
- [ ] Workshop
- [ ] Moderated Discussion
## Description

On August 7th, 2011 I pushed my first commit to my first open source project, Sassy Modular Scale. This project sparked my journey into the budding Sass community and evolved my understanding of software and design as it evolved. On February 16th, 2015 the project came full circle as I helped to re-launch the website that inspired my first few lines of open source code, modularscale.com.
## Speaker Info
- Name      : Scott Kellum
- Location  : Brooklyn, NY
- Contact   : scott@scottkellum.com
##### Social Media:
- Twitter   : [@scottkellum](http://twitter.com/scottkellum)
- GitHub    : [scottkellum](https://github.com/scottkellum)
- Url(s)    : [scottkellum.com](http://scottkellum.com)
##### Bio:

I’m a designer and front end developer at [Vox Media](http://www.voxmedia.com/) working to make amazing products for our readers and writers. I grew up in the suburbs of DC but moved to NYC for school and never moved back. Had a run as a professional type designer at [Darden Studio](http://dardenstudio.com/) and first made my mark on the web at Treesaver. I enjoy cat gifs, hammocks, and great food.
##### Photo:

![Avatar](http://img.pgdn.us/b/profile-9.jpg)

_http://scottkellum.com_

**Comment by elyseholladay** [comment]
Hi Scott! (OK feels weird pasting this to you :stuck_out_tongue: )

Thank you so much for submitting to SassConf this year!

Unfortunately, we weren’t able to select your talk. 

We had an incredible number of submissions this year: 81, in fact, enough to fill up over two weeks of Sassy goodness! But we only have two days, and we couldn’t pick everything.

If you have any questions at all about our selection process, your submission, or anything else at all, please reach out: elyse@sassconf.com and I’ll gladly give you more details.

Again, thank you for submitting. It’s people like you, who are willing to put themselves out there and work hard and submit and give talks that make it possible to even have SassConf. I hope you will submit again next year and continue to be part of the Sass community!

See you in November!
