### ISSUE TITLE
Power to the Front-End: Delivering HTML & CSS as an API

### ISSUE THREAD

**Issue by hagenburger** [SassConf/2015-austin-speaker-cfp#54]
# Power to the Front-End: Delivering HTML & CSS as an API
## Type of Presentation
- [x] Standard Length Talk  
- [ ] Lightning Talk  
- [ ] Workshop  
- [ ] Moderated Discussion
## Description

CSS can’t live without HTML, and HTML almost can’t live without CSS. So, why is it that we split up front-end development into a style guide taking care of the CSS with examples on how to use it, and then an application that implements it?

Not every application developer (back-end or JavaScript) places importance on the details of front-end structure. Instead, they prefer simply to use APIs — mostly with a JSON interface. Instead of interference with the front-end developer’s work, this provides a structured API that only takes care of defined values.

This little detail offers far better possibilies to:
- Document and explain the components
- Test your CSS
- Avoid errors
- Split up between front-end (style) and application code
- Spread your design over several applications
- Upgrade design
- Versioning

I’ll show you what you need to turn your style guide into an API which gives you — as a front-end developer — the full power of the visual part of the website, and how to easily consume them by one or more applications. By having CSS and HTML combined in one place, theming allows more than just adjusting CSS. The API can take care of this.

Afterwards, the applications’s views should not need to be touched for visual reasons anymore. The content and logic are as perfectly separated as we planned them to be at the end of 90s.

(This talk will include real-life examples, like the [Eurucamp style guide API](http://style-guide.eurucamp.org/2015/components.html), where the code is open source.)
## Speaker Info
- Name      : Nico Hagenburger
- Location  : Berlin, Germany
- Contact   : nico@hagenburger.net
##### Social Media:
- Twitter   : [@hagenburger](https://twitter.com/hagenburger) [@LSGorg](https://twitter.com/LSGorg)
- GitHub    : [@hagenburger](https://github.com/hagenburger) [@livingstyleguide](https://github.com/livingstyleguide)
- Dribbble  : [@hagenburger](https://dribbble.com/hagenburger)
- Url(s)    : [hagenburger.net](http://www.hagenburger.net) [quotation-marks.org](http://www.quotation-marks.org) [livingstyleguide.org](http://www.livingstyleguide.org)
##### Bio:

I love Sass, have been having my love affair with it since the colon used to be on the left side of the attribute name. During the day, I work on large, maintainable code bases, style guides, and designing in the browser. Whenever I find a way to automize things, I try to create an open-source solution. It started with [Lemonade/Compass Sprites](https://github.com/hagenburger/lemonade#lemonade-is-deprecated), [Sass Quotation-Marks](http://quotation-marks.org), [Git Routines](https://github.com/hagenburger/git-routines), and the baby I spent most of my time on: the [LivingStyleGuide Gem for Sass](https://github.com/livingstyleguide/livingstyleguide/tree/v2#readme). Just recently, I put my experience on style guide APIs [into an own Gem](https://github.com/hagenburger/styleguide-api) which is already in use to keep [Eurucamp’s](http://style-guide.eurucamp.org/2015/components.html) different applications in sync.

When my computer is actually off, I’m working with interior design, including my collection of vintage subway train parts and signage. I don’t own any part of the train shown on my photo though.
##### Photo:

![Nico Hagenburger](http://www.hagenburger.net/DOWNLOADS/nico-queens.jpg)

**Comment by elyseholladay** [comment]
Hi Nico!

Thank you so much for submitting to SassConf this year!

Unfortunately, we weren’t able to select your talk. 

We had an incredible number of submissions this year: 81, in fact, enough to fill up over two weeks of Sassy goodness! But we only have two days, and we couldn’t pick everything.

If you have any questions at all about our selection process, your submission, or anything else at all, please reach out: elyse@sassconf.com and I’ll gladly give you more details.

Again, thank you for submitting. It’s people like you, who are willing to put themselves out there and work hard and submit and give talks that make it possible to even have SassConf. I hope you will submit again next year and continue to be part of the Sass community!

See you in November!
