### ISSUE TITLE
TypeTuner: A Case Study in Building a Sass Library

### ISSUE THREAD

**Issue by jdsteinbach** [SassConf/2015-austin-speaker-cfp#55]
# TypeTuner: A Case Study in Building a Sass Library
## Type of Presentation

Standard Length Talk
## Description

When you're learning Sass, there are so many awesome libraries available (Susy, Breakpoint, Modular Scale, Bourbon, Compass, etc). It's great that so many people are solving complex problems with complex libraries. Pretty soon, you've got an idea for a complex problem you can solve with Sass! How do you get from that idea to an organized, open library to share?

In this case study, we'll walk through the steps of identifying a real layout pain point, defining requirements for a library to solve that problem, and writing clean, maintainable Sass to meet those requirements.
1. Need for Responsive Typography (including overview of existing solutions)
2. Project Requirements:
   - Base font size varies by breakpoint
   - Type scale varies by breakpoint
   - Type scale increases on intelligent proportions
   - Consistent vertical rhythm
3. Sass-y Solutions
   - Maps for breakpoint data
   - Lists for desired font sizes
   - Loops for size/line-height generation
   - Mixins for reusable rhythm measurements
4. Demo of how to use TypeTuner

Bonus Material
- View a working copy of the [TypeTuner tool (still in revision)](https://github.com/jdsteinbach/typetuner)
## Speaker Info
- Name      : James Steinbach
- Location  : moving to Denver, CO by the time of the conference :sunrise_over_mountains: 
- Contact   : jdsteinbach@gmail.com
##### Social Media:
- Twitter   : [@jdsteinbach](https://twitter.com/jdsteinbach)
- GitHub    : [jdsteinbach](https://github.com/jdsteinbach)
- Url(s)    : [Blog @ jdsteinbach.com](https://jdsteinbach.com)
##### Bio:

I'm a front-end architect with a passion for Sass-organized modular code, meaningful animation, and content-centric semantic markup. When I'm not at work I'm probably spending time with my wife & baby daughter … or, occasionally still at a computer trying out some [fun front-end stuff](https://codepen.io/jdsteinbach).
##### Photo:

![Avatar](http://jamessteinbach.com/img/james-bkgd-750x500.jpg)

_Photo by [Colie Photos](http://coliephotos.com)._

**Comment by elyseholladay** [comment]
Hi James!

Thank you so much for submitting to SassConf this year!

Unfortunately, we weren’t able to select your talk. 

We had an incredible number of submissions this year: 81, in fact, enough to fill up over two weeks of Sassy goodness! But we only have two days, and we couldn’t pick everything.

If you have any questions at all about our selection process, your submission, or anything else at all, please reach out: elyse@sassconf.com and I’ll gladly give you more details.

Again, thank you for submitting. It’s people like you, who are willing to put themselves out there and work hard and submit and give talks that make it possible to even have SassConf. I hope you will submit again next year and continue to be part of the Sass community!

See you in November!
