### ISSUE TITLE
Breaking Free from BootStrap: Responsive Grids with Susy

### ISSUE THREAD

**Issue by jdsteinbach** [SassConf/2015-austin-speaker-cfp#56]
# Breaking Free from BootStrap: Responsive Grids with Susy
## Type of Presentation

Standard Length Talk
## Description

CSS frameworks like Foundation and Bootstrap are opinionated and heavy. They force designers to honor unnecessary constraints, developers to follow arbitrary conventions, and users to wait on bloated page loads. Often, those frameworks are used primarily for one reason: pre-built grids.

By switching to a Sass grid system like Susy, we can free designers to pursue custom grids, save ourselves hours of clean-up, and give our users light, fast pages. 

Outline:
- Concerns with heavy CSS Frameworks
- Basics of Susy
- Advanced features of Susy

[Slide Deck](http://www.slideshare.net/JamesSteinbach/breaking-free-from-bootstrap)
## Speaker Info
- Name      : James Steinbach
- Location  : moving to Denver, CO by the time of the conference :sunrise_over_mountains: 
- Contact   : jdsteinbach@gmail.com
##### Social Media:
- Twitter   : [@jdsteinbach](https://twitter.com/jdsteinbach)
- GitHub    : [jdsteinbach](https://github.com/jdsteinbach)
- Url(s)    : [Blog @ jdsteinbach.com](https://jdsteinbach.com)
##### Bio:

I'm a front-end architect with a passion for Sass-organized modular code, meaningful animation, and content-centric semantic markup. When I'm not at work I'm probably spending time with my wife & baby daughter … or, occasionally still at a computer trying out some [fun front-end stuff](https://codepen.io/jdsteinbach).
##### Photo:

![Avatar](http://jamessteinbach.com/img/james-bkgd-750x500.jpg)

_Photo by [Colie Photos](http://coliephotos.com)._

**Comment by elyseholladay** [comment]
Hi James!

Thank you so much for submitting to SassConf this year!

Unfortunately, we weren’t able to select your talk. 

We had an incredible number of submissions this year: 81, in fact, enough to fill up over two weeks of Sassy goodness! But we only have two days, and we couldn’t pick everything.

If you have any questions at all about our selection process, your submission, or anything else at all, please reach out: elyse@sassconf.com and I’ll gladly give you more details.

Again, thank you for submitting. It’s people like you, who are willing to put themselves out there and work hard and submit and give talks that make it possible to even have SassConf. I hope you will submit again next year and continue to be part of the Sass community!

See you in November!
