### ISSUE TITLE
Front-End Tool Overload: or How I Learned to Stop Worrying and Love to Learn

### ISSUE THREAD

**Issue by jdsteinbach** [SassConf/2015-austin-speaker-cfp#57]
# Front-End Tool Overload: or How I Learned to Stop Worrying and Love to Learn
## Type of Presentation

Standard Length Talk
## Description

Remember when front-end development meant writing HTML, CSS & and a little JS? While those skills are still the core of a front-end workflow, they’re often surrounded by dozens of other tools. CSS preprocessors & postprocessors, JS task runners, virtual environments, and version control systems are just a few of the many additional tools that undergird front-end workflows. To many new developers (and even some old ones!), this proliferation of tools creates a sense of overwhelming pressure. It feels like it’s no longer enough to write good code.

We don’t need to live under the pressure of dev-tool overload. This talk will talk about how to evaluate new tools before using them, how to gain proficiency, and most importantly, how to deal with the stress and pressure of being overwhelmed by new information.
## Speaker Info
- Name      : James Steinbach
- Location  : moving to Denver, CO by the time of the conference :sunrise_over_mountains: 
- Contact   : jdsteinbach@gmail.com
##### Social Media:
- Twitter   : [@jdsteinbach](https://twitter.com/jdsteinbach)
- GitHub    : [jdsteinbach](https://github.com/jdsteinbach)
- Url(s)    : [Blog @ jdsteinbach.com](https://jdsteinbach.com)
##### Bio:

I'm a front-end architect with a passion for Sass-organized modular code, meaningful animation, and content-centric semantic markup. When I'm not at work I'm probably spending time with my wife & baby daughter … or, occasionally still at a computer trying out some [fun front-end stuff](https://codepen.io/jdsteinbach).
##### Photo:

![Avatar](http://jamessteinbach.com/img/james-bkgd-750x500.jpg)

_Photo by [Colie Photos](http://coliephotos.com)._

**Comment by elyseholladay** [comment]
Hi James! 

Thank you so much for submitting to SassConf this year!

Unfortunately, we weren’t able to select your talk. 

We had an incredible number of submissions this year: 81, in fact, enough to fill up over two weeks of Sassy goodness! But we only have two days, and we couldn’t pick everything.

If you have any questions at all about our selection process, your submission, or anything else at all, please reach out: elyse@sassconf.com and I’ll gladly give you more details.

Again, thank you for submitting. It’s people like you, who are willing to put themselves out there and work hard and submit and give talks that make it possible to even have SassConf. I hope you will submit again next year and continue to be part of the Sass community!

See you in November!
