### ISSUE TITLE
Going Static, with Middleman

### ISSUE THREAD

**Issue by tdreyno** [SassConf/2015-austin-speaker-cfp#58]
# Going Static, with Middleman
## Type of Presentation
- [ ] Standard Length Talk
- [ ] Lightning Talk
- [x] Workshop
- [ ] Moderated Discussion
## Description

Middleman is a static site development platform written in Ruby. With static development, you can build very fast websites, without any security concerns that will be extremely cheap and ease to host. For those who consider themselves mostly frontend, Middleman provides a simple platform for combining Sass, JS and HTML without much extra work.

When picking up a new platform, the first couple days can be the toughest. Installing Ruby, dealing with Bundler and learning the basics can feel like a lot of work without any immediate payoff. This workshop will compress that learning curve into 4 hours and attendees will leave ready to build their static sites.

There will be a short introductory talk on platform, during which attendees will pray that the conference wifi works well enough to install Ruby. If the workshops are pre-registered, maybe we could suggest they install before. Either way, we will provide time for the installation process.

The workshop will be a walkthrough of building a small blog using Middleman & Susy. The output will be a group deployment (again, pray to the gods of wifi) of everyone's first post to a shared Amazon S3 bucket.
### Workshops: Coding Exercise

Attendees will start a new Middleman project, set up the blogging and Susy extensions, write a small post in Markdown and prepare the result for building and deployment.
## Speaker Info
- Name      : Thomas Reynolds
- Location  : Portland, OR
- Contact   : me@tdreyno.com
##### Social Media:
- Twitter   : [@tdreyno]
- GitHub    : [tdreyno]
- Url(s)    : [tdreyno.com, middlemanapp.com]
##### Bio:

I'm Thomas Reynolds, the creator of Middleman and a Technical Director at Instrument (a marketing agency in Portland, OR). I split my days between triaging Github tickets on a very active project, educating and mentoring developers at work and trying to tired out my 3 dogs.
##### Photo:

![Avatar](https://s3.amazonaws.com/f.cl.ly/items/0D1i053H3C082u2Q0f1r/test.jpg)

**Comment by sandstrom** [comment]
Sounds interesting! :boat: 

Static websites are especially useful for front-end people. It's a super-power for front-end devs/designers to be able to deploy (instead of being dependent on other).

I've heard this is the tool that http://mailchimp.com/ use.

**Comment by elyseholladay** [comment]
Hi Thomas!

Thank you so much for submitting to SassConf this year!

Unfortunately, we weren’t able to select your workshop. 

We had an incredible number of submissions this year: 81, in fact, enough to fill up over two weeks of Sassy goodness! But we only have two days, and we couldn’t pick everything.

If you have any questions at all about our selection process, your submission, or anything else at all, please reach out: elyse@sassconf.com and I’ll gladly give you more details.

Again, thank you for submitting. It’s people like you, who are willing to put themselves out there and work hard and submit and give talks that make it possible to even have SassConf. I hope you will submit again next year and continue to be part of the Sass community!

See you in November!
