### ISSUE TITLE
Improve Your Email Development Workflow with Sass

### ISSUE THREAD

**Issue by briangraves** [SassConf/2015-austin-speaker-cfp#62]
# Improve Your Email Development Workflow with Sass
## Type of Presentation (required)

[ x ] Standard Length Talk
[  ] Lightning Talk
[  ] Workshop
[  ] Moderated Discussion
## Description (required)

Whether you’re a Fortune 500 company or part a two-person team launching your first web app, email is one of the most important tools for reaching your users and customers. At the same time, it is one of the most dreaded things developers have to work on. My talk will cover setting up a workflow that brings in modern tools that will have you regularly shipping engaging, modular and mobile-friendly emails with less hassle and without the normal headaches. Attendees will learn how to bring modern tooling into what is typically seen as an outdated medium. They will learn how to set up an easy to use modular framework that includes build tools such as Sass and Grunt.
## Speaker Info (required)
- Name      : Brian Graves
- Location  : Kansas City, MO
- Contact   : bgraves@degdigital.com
##### Social Media:
- Twitter   : [@briangraves](http://www.twitter.com/briangraves)
- GitHub    : [briangravesl](https://github.com/briangraves)
- Url(s)    : [brianleegraves.com](http://www.brianleegraves.com)
##### Bio:

A UI designer and developer who's passionate about design and the process behind it, Brian is a strong proponent of iterative work, collaborative efforts, and user first design. He is currently the UI team lead at DEG where he does cross-channel design and development work for a range of major clients and brands. In addition to his  9-5, Brian has several side projects including Yeo+Lab, Responsive Email Patterns and Responsive Email Resources and speaks and writes regularly.
##### Photo:

![Avatar](http://brianleegraves.com/Headshots/Professional.jpg)

http://brianleegraves.com/Headshots/Professional.jpg

**Comment by elyseholladay** [comment]
Hi Brian!

Thank you so much for submitting to SassConf this year!

Unfortunately, we weren’t able to select your talk. 

We had an incredible number of submissions this year: 81, in fact, enough to fill up over two weeks of Sassy goodness! But we only have two days, and we couldn’t pick everything.

If you have any questions at all about our selection process, your submission, or anything else at all, please reach out: elyse@sassconf.com and I’ll gladly give you more details.

Again, thank you for submitting. It’s people like you, who are willing to put themselves out there and work hard and submit and give talks that make it possible to even have SassConf. I hope you will submit again next year and continue to be part of the Sass community!

See you in November!
