### ISSUE TITLE
Workshop: Turn Your Style Guide Into a Testable Stable API

### ISSUE THREAD

**Issue by hagenburger** [SassConf/2015-austin-speaker-cfp#63]
# Turn Your Style Guide Into a Testable Stable API
## Type of Presentation
- [ ] Standard Length Talk  
- [ ] Lightning Talk  
- [x] Workshop  
- [ ] Moderated Discussion
## Description

This workshop will show you how to create a front-end style guide with:
- Atoms for reusability within components
- Components that are available to the application with a defined data structure
- Regression testing of the style guide
- Versioning of styles and keeping consuming applications up-to-date
- Delivering and consuming of components/templates
- Themes that may have different CSS and HTML
- Automatic deployment

As an outcome of this workshop you will get:
- Application code free of HTML—let the style guide take care of it, the application only knows:
  - The template/component name
  - The data accepted by the template/component
  - The version currently used
- You can always be sure that every HTML matches the right version of the corresponding CSS.
- A separation of concerns between the visual front-end and the application developer.

Extras:
- Let your style guide match your corporate styles.
- Tricks on how to display elements within a style guide.
## Speaker Info
- Name      : Nico Hagenburger
- Location  : Berlin, Germany
- Contact   : nico@hagenburger.net
##### Social Media:
- Twitter   : [@hagenburger](https://twitter.com/hagenburger) [@LSGorg](https://twitter.com/LSGorg)
- GitHub    : [@hagenburger](https://github.com/hagenburger) [@livingstyleguide](https://github.com/livingstyleguide)
- Dribbble  : [@hagenburger](https://dribbble.com/hagenburger)
- Url(s)    : [hagenburger.net](http://www.hagenburger.net) [quotation-marks.org](http://www.quotation-marks.org) [livingstyleguide.org](http://www.livingstyleguide.org)
##### Bio:

I love Sass, have been having my love affair with it since the colon used to be on the left side of the attribute name. During the day, I work on large, maintainable code bases, style guides, and designing in the browser. Whenever I find a way to automize things, I try to create an open-source solution. It started with [Lemonade/Compass Sprites](https://github.com/hagenburger/lemonade#lemonade-is-deprecated), [Sass Quotation-Marks](http://quotation-marks.org), [Git Routines](https://github.com/hagenburger/git-routines), and the baby I spent most of my time on: the [LivingStyleGuide Gem for Sass](https://github.com/livingstyleguide/livingstyleguide/tree/v2#readme). Just recently, I put my experience on style guide APIs [into an own Gem](https://github.com/hagenburger/styleguide-api) which is already in use to keep [Eurucamp’s](http://style-guide.eurucamp.org/2015/components.html) different applications in sync.

When my computer is actually off, I’m working with interior design, including my collection of vintage subway train parts and signage. I don’t own any part of the train shown on my photo though.
##### Photo:

![Nico Hagenburger](http://www.hagenburger.net/DOWNLOADS/nico-queens.jpg)

**Comment by elyseholladay** [comment]
Hi Nico!

Thank you so much for submitting to SassConf this year!

Unfortunately, we weren’t able to select your workshop. 

We had an incredible number of submissions this year: 81, in fact, enough to fill up over two weeks of Sassy goodness! But we only have two days, and we couldn’t pick everything.

If you have any questions at all about our selection process, your submission, or anything else at all, please reach out: elyse@sassconf.com and I’ll gladly give you more details.

Again, thank you for submitting. It’s people like you, who are willing to put themselves out there and work hard and submit and give talks that make it possible to even have SassConf. I hope you will submit again next year and continue to be part of the Sass community!

See you in November!
