### ISSUE TITLE
My 100 Day Art Affair with Sass and Trigonometry

### ISSUE THREAD

**Issue by ThisIsJohnBrown** [SassConf/2015-austin-speaker-cfp#65]
# My 100 Day Art Affair with Sass and Trigonometry
## Type of Presentation

[x] Standard Length Talk
## Description (required)

You’re working with CSS every day. You’re making the unstyled structure of the web look amazing. But when was the last time you created something unique, beautiful, **and** personal?

I am currently on a 100 day project where I am making art with Sass. The experiments have been ordered, glitchy, painterly, mathematical, and other adjectives. I would love to show some of the strange things that are possible with Sass, a bit of trigonometry, and a desire to create, and demonstrate a few amazing tricks I have learned along the way to make art from divs.

Not only is the destination amazing (it’s art, after all), the journey is great as well, because in your quest to create, you’ll learn new techniques that will help you in your regular work. Working with parameters like box-shadow or gradients in a way that breaks convention forces you to understand it more. The next time a project comes up, you’ll get to apply your hard won knowledge of nested animations and blend modes to make the web pop!

So let’s talk about code art! When attendees leave, they'll be inspired to create delightfully styled and elegantly animated pieces of art, with Sass and beyond!
## Speaker Info (required)
- Name      : John Brown
- Location  : Portland, OR
- Contact   : thisisjohnbrown@gmail.com
##### Social Media:
- Twitter   : [@thisisjohnbrown](http://twitter.com/thisisjohnbrown)
- Instagram : [thisisjohnbrown](http://instagram.com/thisisjohnbrown)
- GitHub    : [thisisjohnbrown](http://github.com/thisisjohnbrown)
- Url(s)    : [thisisjohnbrown.com](http://thisisjohnbrown.com), [100 Day Project](http://codepen.io/collection/naMNgw/)
##### Bio:

I'm a fullstack developer, which means I like to do a little bit of a lot of things. All my knowledge goes into making code art, though. I co-organize [PDX Creative Coders](http://meetup.com/PDX-Creative-Coders/), run several community code art projects, and I work at [Instrument](http://instrument.com) as a Technical Director.
##### Photo:

![Avatar](http://makeart.s3.amazonaws.com/johnBrown.png)

**Comment by elyseholladay** [comment]
Hi John! 

Thank you so much for submitting to SassConf this year!

Unfortunately, we weren’t able to select your talk. 

We had an incredible number of submissions this year: 81, in fact, enough to fill up over two weeks of Sassy goodness! But we only have two days, and we couldn’t pick everything.

If you have any questions at all about our selection process, your submission, or anything else at all, please reach out: elyse@sassconf.com and I’ll gladly give you more details.

Again, thank you for submitting. It’s people like you, who are willing to put themselves out there and work hard and submit and give talks that make it possible to even have SassConf. I hope you will submit again next year and continue to be part of the Sass community!

See you in November!
