### ISSUE TITLE
Quantity Ordering

### ISSUE THREAD

**Issue by drewminns** [SassConf/2015-austin-speaker-cfp#66]
## Submission Template
# Quantity Ordering
## Type of Presentation (required)

[ x ] Standard Length Talk
[  ] Lightning Talk
[  ] Workshop
[  ] Moderated Discussion
## Description (required)

Websites are dynamic, we are able to display content based on conditional statements in JavaScript. However we never really rely on CSS, the presentational layer of our websites to define how our content is ordered. 

Utilizing Quantity Queries to count elements in a page, and then applying Flexbox ordering, we can change the order and structure of our content via CSS. Removing the need for a programming language to define the presentation of our content, we can return that task to CSS, a presentational language.
### Target Audience

Developers and designers of all levels, particularly users of static sites and static site generators.

Fine Print:
- Blog post: http://reallygood.work/05/02/css-supply-demand/ 5k reads and mentioned on Smashing Magazine.
## Speaker Info (required)
- Name      : Drew Minns
- Location  : Toronto, ON Canada
- Contact   : dminns@gmail.com
##### Social Media:
- Twitter   : [@drewisthe](https://twitter.com/drewisthe)
- GitHub    : [drewminns](https://github.com/drewminns)
- Url(s)    : [drewminns.com](www.drewminns.com), [reallygood.work](http://reallygood.work)
##### Bio:

Passionate about education and technology and only interested in making things that make people say, 'Whoa'. Currently changing the traditional tech education system with [HackerYou](http://hackeryou.com) as a Lead Instructor and Developer, I'm passionate about the power of CSS and presentational tooling. I'm a published author working with [Six Revisions](http://sixrevisions.com) and [Smashing Magazine](http://smashingmagazine.com) to instruct and explore the power of Front End development.
##### Photo:

![Avatar](http://www.drewminns.com/images/profile.jpg)

---

Next: [Mentoring & Speaker Prep](https://github.com/SassConf/2015-speaker-cfp/blob/master/docs/mentoring-speaker-prep.md)

**Comment by elyseholladay** [comment]
Hi Drew!

Thank you so much for submitting to SassConf this year!

Unfortunately, we weren’t able to select your talk. 

We had an incredible number of submissions this year: 81, in fact, enough to fill up over two weeks of Sassy goodness! But we only have two days, and we couldn’t pick everything.

If you have any questions at all about our selection process, your submission, or anything else at all, please reach out: elyse@sassconf.com and I’ll gladly give you more details.

Again, thank you for submitting. It’s people like you, who are willing to put themselves out there and work hard and submit and give talks that make it possible to even have SassConf. I hope you will submit again next year and continue to be part of the Sass community!

See you in November!
