### ISSUE TITLE
Get Good at Gulp - Workshop

### ISSUE THREAD

**Issue by wesbos** [SassConf/2015-austin-speaker-cfp#67]
# Title of Presentation

Get Good at Gulp
## Type of Presentation
- [ ] Standard Length Talk
- [ ] Lightning Talk
- [x] Workshop
- [ ] Moderated Discussion
## Description (required)

All modern websites and web applications require a build step in which we compile, compress and clean the code and assets in our project.

Gulp.js is a task runner that allows us to quickly create and customize build systems for any type of project. Whether you are building a JavaScript heavy application, totally diving into using SVGs or building a complex CSS3 website, learning Gulp.js is an investment any front end developer needs to make.

This workshop will take users from never having used gulp, to creating totally custom build systems. The goals of this workshop are:
- Full understanding of Gulp, with the ability to create totally customized build systems
- Increased Developer Efficiency - build it once and have your tooling support you in solving problems rather than manual tasks
- Creation of better, cleaner codebases
- Faster loading websites, smaller overall footprints 

And will include:
## CSS
- Compiling Sass, Stylus or Less into CSS
- Start using CSS4 features today CSS Next
- Automatically prefixing CSS with Autoprefixer
- Removing unused CSS from our projects
## Code Quality + Performance
- Compress all your JPG, PNG and GIF files before launching a site
- Inline SVG files for easy CSS manipulation and fast loading
- Run Linters on languages which check for coding errors
## JavaScript
- Start writing next-generation ECMAScript 6 features today and _transpile_ into browser supported ES5 with Babel.js
- Concatenate, Compress and Obfuscate JavaScript into a single file
- Work with Sourcemaps for easy debugging on compressed and transpiled JavaScript files
## Workflow Optimizations
- Live edit with BrowserSync to easily test, reload and sync website changes across multiple devices
- Compile Jade or Haml templates and partials into HTML
- Create watch that run when files are changed
- Error Handling and Desktop Notifications
### Workshops: Coding Exercise (required for workshops only)

This workshop will have users both use existing Gulp scripts as well as craft their own from scratch. It will include a number of code alongs as well as exercises in which users will be challenged to build their own end-to-end Gulp.js build system. 
## Speaker Info
- Name      : Wes Bos
- Location  : Hamilton, Ontario, Canada
- Contact   : [wes@wesbos.com](mailto:wes@wesbos.com)
##### Social Media:
- Twitter   : [@wesbos](http://twitter.com/wesbos)
- GitHub    : [wesbos](http://github.com/wesbos)
- Url(s)    : [wesbos.com](WesBos.com), 
##### Bio:

Wes Bos is an independent full stack developer and designer from Toronto who spends most of his time hacking on HTML5, CSS3, Node.js building applications entirely in JavaScript. Wes is a lead instructor for [Ladies Learning Code](http://ladieslearningcode.com) and [Hacker You](http://hackeryou.com) where he teaches students and leads workshops on how to build websites and break into the web industry.

Wes is passionate about web tooling - he is the Author of [Sublime Text Power User](http://SublimeTextBook.com) and an upcoming book + video series on Gulp. He also recently released a free video series on working in the Command Line for front end developers - http://commandlinepoweruser.com/
##### Photo:

![Handsome, Eh?](http://wes.io/b5WN/content)

**Comment by wesbos** [comment]
FWIW - I'm running a similar training at Fronteers in Amsterdam and tickets are almost sold out after 3 days of being available.

**Comment by elyseholladay** [comment]
Hi Wes!

Thank you so much for submitting to SassConf this year!

Unfortunately, we weren’t able to select your workshop. (Hopefully you'll be able to come do it as a paid add-on workshop, though!)

We had an incredible number of submissions this year: 81, in fact, enough to fill up over two weeks of Sassy goodness! But we only have two days, and we couldn’t pick everything.

If you have any questions at all about our selection process, your submission, or anything else at all, please reach out: elyse@sassconf.com and I’ll gladly give you more details.

Again, thank you for submitting. It’s people like you, who are willing to put themselves out there and work hard and submit and give talks that make it possible to even have SassConf. I hope you will submit again next year and continue to be part of the Sass community!

See you in November!
