### ISSUE TITLE
40 Ways to Configure your Sass

### ISSUE THREAD

**Issue by roytomeij** [SassConf/2015-austin-speaker-cfp#7]
#40 Ways to Configure your Sass
## Type of Presentation

Standard Length Talk
## Description

The most common way to add configuration settings to your Sass code, and the one used by most frameworks and libraries, is to use good ol' `$variables` with simple values. Let's explore what other options we have, and see how we can put them to use.

While 40 ways may be exaggerating a bit (it got your attention though), here's some of what we'll look into:
- Simple configuration variables
- Configuration lists
- Configuration maps
- Configuration mixins
- Configuration functions
- _Ascii art configuration grids_
- Sharing configuration settings
- And more!

These techniques can be used to configure and easily change things like theming, grids, text direction and typography. Or they can be used to write your own _Sass Architecture DSL™_, dynamically creating CSS based on smart configuration settings. All of that will be part of this talk, including the live coding to prove these concepts (could) work.

Most of the above can be put to use immediately, while some of it is more theoretical in nature. Everything comes with working demo code, making use of advanced Sass features. This talk will be a deep dive into something that (on the surface) looks as simple as throwing in some variables and `@if`/`@else`.
### Brand new content

This is a brand new talk. The demo code uses some (small) libraries written specially for this talk, made public under the MIT license. It's a great start for anyone who wants to use smarter configuration settings without having to code from scratch.
### Target audience

This talk is aimed towards intermediate and advanced users of Sass who want to know more about creative use of data types, control structures and functions. It's great for people who maintain a single codebase to style multiple sites with theming, including themes alternating between left-to-right and right-to-left lay-outs.

It's a great fit for SassConf, because it goes into so much detail (while not losing sight of the bigger picture) on both language and architecture levels. A dive this deep is probably too much for most other conferences. The Sasstronauts at SassConf can handle it though.
## Speaker Info
- Name: Roy Tomeij
- Location: Amsterdam, The Netherlands
- Contact: contact@roytomeij.com
##### Social Media:
- Twitter: [@roy](https://twitter.com/roy)
- GitHub: [roytomeij](https://github.com/roytomeij)
- Urls:
  - [roytomeij.com](http://roytomeij.com)
  - [lanyrd.com/roy](http://lanyrd.com/profile/roy/)
##### Bio:

Roy is a speaker, trainer and front-end architect from Amsterdam, The Netherlands. He started using Sass early 2007 and hasn't written any plain ol' CSS since. By day he works on AppSignal, by night he shoots through the sky as a Sasstronaut.
##### Photo:

Higher resolution upon request.

![Roy Tomeij](http://static.roytomeij.com/roy.jpg)

**Comment by davidkpiano** [comment]
:+1: This sounds like an interesting talk - I'd definitely want to see it. The ASCII art configuration settings sounds intriguing. Would you be providing examples and/or real-life usage of the various Sass configuration organizations?

**Comment by roytomeij** [comment]
Thanks for the input @davidkpiano. Definitely going to include real-life examples on when to use what, plus working code to implement the learnings in your own projects (word to the wise: you'll want to _not_ use some of these techniques in production :wink:).

**Comment by roytomeij** [comment]
_Updated this proposal with some more details._

**Comment by elyseholladay** [comment]
Hi Roy!

Thank you so much for submitting to SassConf this year!

Unfortunately, we weren’t able to select your talk. 

We had an incredible number of submissions this year: 81, in fact, enough to fill up over two weeks of Sassy goodness! But we only have two days, and we couldn’t pick everything.

If you have any questions at all about our selection process, your submission, or anything else at all, please reach out: elyse@sassconf.com and I’ll gladly give you more details.

Again, thank you for submitting. It’s people like you, who are willing to put themselves out there and work hard and submit and give talks that make it possible to even have SassConf. I hope you will submit again next year and continue to be part of the Sass community!

See you in November!
