### ISSUE TITLE
How do you solve a problem like "Front End Developer"

### ISSUE THREAD

**Issue by mpiotrowicz** [SassConf/2015-austin-speaker-cfp#70]
# How do you solve a problem like "Front End Developer"
## Type of Presentation (required)

[x] Standard Length Talk
## Description (required)

As a discipline, front end development (FED) has recently seen enormous growth as new design patterns, build tools, and libraries and frameworks emerge and mature. Given this wide range of topics, FED can start meaning different things to different people, and it can be easy to lose track of what exactly a “front end developer” does on any given team and why it's important.
At Shopify, we’ve been exploring the role more closely as our FED team continues to grow. In this talk, I will share my perspective on front end development and discuss how by investing in shared tools like design standards, processes, and style guides, we’ve been able to find common focus for our team and a stronger understanding of our role across disciplines. “Front end developer” can be an ambiguous title - here’s one team’s approach to finding some clarity.
## Speaker Info (required)
- Name      : Monika Piotrowicz
- Location  : Toronto, Canada
- Contact   : monika@shopify.com
##### Social Media:
- Twitter   : [@monsika](twitter.com/monsika)
- GitHub    : [mpiotrowicz](https://github.com/mpiotrowicz)
- Url(s)    : [slideshare.net/mpiotrowicz/](slideshare.net/mpiotrowicz/)
##### Bio:

Monika Piotrowicz is a Front End Development Lead for Shopify, a commerce platform that helps merchants manage all parts of their commerce business. Her passion has always been in using HTML, CSS, and JavaScript to build exceptional and inclusive interfaces for users. Most at home when collaborating across disciplines, she’s committed to bridging the space between design and engineering so that teams can focus on solving the right set of problems. At Shopify, she’s helped establish the front end discipline within the Growth and Marketing teams, and helps lead new theme development, Shopify.com, and other growth initiatives.
##### Photo:

![Avatar](https://pbs.twimg.com/profile_images/598584219174998016/NIaxyivu.jpg)

**Comment by elyseholladay** [comment]
Hi Monika! 

Thank you so much for submitting to SassConf this year!

Unfortunately, we weren’t able to select your talk. 

We had an incredible number of submissions this year: 81, in fact, enough to fill up over two weeks of Sassy goodness! But we only have two days, and we couldn’t pick everything.

If you have any questions at all about our selection process, your submission, or anything else at all, please reach out: elyse@sassconf.com and I’ll gladly give you more details.

Again, thank you for submitting. It’s people like you, who are willing to put themselves out there and work hard and submit and give talks that make it possible to even have SassConf. I hope you will submit again next year and continue to be part of the Sass community!

See you in November!
