### ISSUE TITLE
The journey to a fully-scalable component library

### ISSUE THREAD

**Issue by kretzm** [SassConf/2015-austin-speaker-cfp#74]
# Title of Presentation

The journey to a fully-scalable component library
## Type of Presentation

[ x ] Standard Length Talk
[  ] Lightning Talk
[  ] Workshop
[  ] Moderated Discussion
## Description

After building the first fully responsive telecommunications website in Canada, our framework and process needed to evolve. We realized that our initial Sass framework wasn’t scaling, our re-usable patterns were not being re-used correctly, and new components were being built in silos. As a result, developers were left to pull code from multiple pages, product owners had to oversee different implementations of the same feature, and the global codebase became fragmented and hard to manage. 

Our solution was to create a component library which would act as a singular reference for global element implementation, standards and conventions. It would also handle the distribution of components to internal teams and external vendors across the country. This approach gives developers a resource of components which is managed and updated in one place. The focus is put back on the building of pages or apps, and less on figuring out how to make a component work for their individual case.

This talk will dive into the architectural strategies and solutions used to build our component library (specifically the Sass aspects), which include;
- Architectural structure of our Sass system
- Abstracting branding/theme from components
- High-level implications of adopting BEM
- Integrating a component library into different web properties
- Maintaining and updating components

The purpose of this talk is not to focus on “what” the solution is, but rather “why" did we make these decisions and “how” did we implement them. Our build, measure, learn process allows us to consistently refine our solutions as we test on real customer facing products. I'm excited to share what we’ve discovered thus far.
## Speaker Info
- Name      : Mike Kretz
- Location  : Toronto, Canada
- Contact   : mkretz@nascentdigital.com
##### Social Media:
- Twitter   : [@kretzm](https://twitter.com/kretzm)
- GitHub    : [Github](https://github.com/kretzm)
- Url(s)    : http://michaelkretz.com
##### Bio:

Mike Kretz is a front-end developer with [Nascent](http://www.nascentdigital.com), a Toronto-based digital agency. His passion is working with large-business clients and startups to build their front-end systems and hone their working process. When he’s not hacking away in HTML, Sass and JavaScript frameworks, he’s scouring the web for Scandinavian interior design inspiration and posting it up on his Tumblr.
##### Photo:

![Avatar](http://michaelkretz.com/images/workpic.jpg)

**Comment by elyseholladay** [comment]
Hi Mike! 

Thank you so much for submitting to SassConf this year!

Unfortunately, we weren’t able to select your talk. 

We had an incredible number of submissions this year: 81, in fact, enough to fill up over two weeks of Sassy goodness! But we only have two days, and we couldn’t pick everything.

If you have any questions at all about our selection process, your submission, or anything else at all, please reach out: elyse@sassconf.com and I’ll gladly give you more details.

Again, thank you for submitting. It’s people like you, who are willing to put themselves out there and work hard and submit and give talks that make it possible to even have SassConf. I hope you will submit again next year and continue to be part of the Sass community!

See you in November!
