### ISSUE TITLE
Syndicating Sass & Other Front End Assets

### ISSUE THREAD

**Issue by JohnRiv** [SassConf/2015-austin-speaker-cfp#79]
# Syndicating Sass & Other Front End Assets
## Type of Presentation

[ x ] Standard Length Talk
[  ] Lightning Talk
[  ] Workshop
[  ] Moderated Discussion
## Description

Comcast is working to unify and standardize its UX. But how can a large company ensure style and UX consistency across multiple web properties, applications, and teams? Dependency abstraction! Through package managers like Ruby gems, bower components, and NPM modules, Sass-based styles can be abstracted into a semantically versioned external dependency shared by multiple teams and codebases. In this presentation, we'll outline the X1 web application team's efforts to syndicate its next-generaton UI styles to other Comcast web applications as a Ruby gem. We'll cover technology, process, success stories, pitfalls, and shortcomings.
## Speaker Info
- Name : John Riviello
- Location : Philadelphia, PA
- Contact : john_riviello@comcast.com
## 
- Name : Mike Ball
- Location : Philadelphia, PA
- Contact : michael_ball@comcast.com
##### Social Media:
- Twitter   : [@JohnRiv](https://twitter.com/JohnRiv)
- GitHub   : [JohnRiv](https://github.com/JohnRiv)
## 
- Twitter   : [@clapexcitement](https://twitter.com/clapexcitement)
- GitHub   : [mdb](https://github.com/mdb)
##### Bios:

John Riviello is a Distinguished Engineer and Lead Frontend Developer at Comcast where he works on the XFINITY customer websites and web apps. In his free time, he prefers surfing waves over surfing the internet.

Mike Ball is a Philadelphia-based software developer and designer. He currently works for Comcast where he helps build web-based TV and video streaming applications. He is also a Philly.rb co-organizer and an avid surfer.
##### Photos:

![John Riviello](http://riviello.net/photos/john/john-riviello_500x500.jpg)

![Mike Ball](https://pbs.twimg.com/profile_images/1453153493/headshot_400x400.jpg)

**Comment by elyseholladay** [comment]
Hi John and Mike! 

Thank you so much for submitting to SassConf this year!

Unfortunately, we weren’t able to select your talk. 

We had an incredible number of submissions this year: 81, in fact, enough to fill up over two weeks of Sassy goodness! But we only have two days, and we couldn’t pick everything.

If you have any questions at all about our selection process, your submission, or anything else at all, please reach out: elyse@sassconf.com and I’ll gladly give you more details.

Again, thank you for submitting. It’s people like you, who are willing to put themselves out there and work hard and submit and give talks that make it possible to even have SassConf. I hope you will submit again next year and continue to be part of the Sass community!

See you in November!
