### ISSUE TITLE
IE the browser every one loves to hate.

### ISSUE THREAD

**Issue by rmjames** [SassConf/2015-austin-speaker-cfp#80]
# Title of Presentation (required)

IE Internets most wanted.
## Type of Presentation (required)

[ x ] Standard Length Talk
[ x ] Lightning Talk
[  ] Workshop
[  ] Moderated Discussion
## Description (required)

We have all been through it, we have all said "I want to use this new feature to solve this particular problem, but IE doesn't support it". You then check [Can I use](http://caniuse.com), and discover it's supported in every other browser but IE. What's a dev to do now, be a maverick and use those new feature and call it a day. Or maybe a resposible Dev(maverick) and find the proper fall backs and polyfills for those features. Or as many people are 'forced to', they opt to not use them at all. "hey can I", "Yeah?!?", "No?!?", "Aww Shucks!!". This very same scenario is played out in many web projects. 

I want to go into how the developement life cycle of browsers indirectly helps dictate the way developers code and develop for the web. Why many developers prefer developing for one browser over the other (i.e Chrome). How we even got to this state!!. At the end of the talk, attendees will be able to take away: 

*The "Browser Wars" of yesteryear
*How browsers implement new feature.
*How they are even considered. 
*What developers can do to help experimental feature become implemented.
*Why is it important to use these new features.
## Speaker Info (required)
- Name      : Robert James
- Location  : Brooklyn, NY
- Contact   : [rma.james@gmail.com](mailto:rma.james@gmail.com)
##### Social Media:
- Twitter   : [@bkrjames](https://twitter.com/bkrjames)
- GitHub    : [github.com/rmjames](https://github.com/rmjames)
- Url(s)    : [robertjames.cc](http://robertjames.cc)
##### Bio:

I'm a Brooklyn based developer who likes teaching and developing for the web.
##### Photo:

![Avatar](http://fewd.us/FEWDpress/wp-content/uploads/2015/01/alumni-headshots-244.jpg)

**Comment by misscs** [comment]
What interests me about the talk is learning more about how browsers implement features. This talk reminds me of the recent talks on CSS colors—a bit of history and fun in one.

**Comment by elyseholladay** [comment]
Hi Robert!

Thank you so much for submitting to SassConf this year!

Unfortunately, we weren’t able to select your talk. 

We had an incredible number of submissions this year: 81, in fact, enough to fill up over two weeks of Sassy goodness! But we only have two days, and we couldn’t pick everything.

If you have any questions at all about our selection process, your submission, or anything else at all, please reach out: elyse@sassconf.com and I’ll gladly give you more details.

Again, thank you for submitting. It’s people like you, who are willing to put themselves out there and work hard and submit and give talks that make it possible to even have SassConf. I hope you will submit again next year and continue to be part of the Sass community!

See you in November!
