### ISSUE TITLE
Font Features Forever

### ISSUE THREAD

**Issue by kennethormandy** [SassConf/2015-austin-speaker-cfp#81]
# Font Features Forever
## Type of Presentation
- [x] Standard Length Talk
- [x] Lightning Talk
- [ ] Workshop
- [ ] Moderated Discussion
## Description

Advanced typographic features allow designers, developers, and writers to improve the communication of their text, increase the perceived authority of writing on screens, and are actually necessary for properly displaying certain languages. On the web, CSS’ `font-feature-settings` provides access to these features: ligatures, kerning, and many others less well known. Despite their importance and age, there are five hurdles that must be overcome to properly use these features. You must:
1. Select a typeface with additional design considerations in the font
2. Serve the font, without losing these additional features along the way
3. Consider and mitigate the performance issues incurred
4. Work around the lack of browser support for certain CSS syntaxes (spoiler: Safari hates you)
5. Apply the features in the typographically appropriate situations

This talk navigates these challenges, with the help of my own coping mechanism: open source Sass and JavaScript-based projects I’ve collaborated on and found that aim and make advanced web typography friendlier by default. This includes [Lost Type Co-op](http://www.losttype.com/font/?name=lavanderia)’s OpenType font tester, Bram Stein’s [State of Web Type](http://stateofwebtype.com/) and [Font Face Observer](https://github.com/bramstein/fontfaceobserver), and my own [Normalize-OpenType.css stylesheet](https://github.com/kennethormandy/normalize-opentype-css).

Both a technical talk and a piece of typographic criticism, this presentation suggests practical, short term solutions to the problem, while placing them in a large discussion of reading on the web.
## Additional information

I tend to give my talks at informal, local meetups so I can refine tem before presenting it at a larger event like SassConf. It won’t have been presented at a conference or recorded before, however.
## Speaker Info
- Name      : Kenneth Ormandy
- Location  : Vancouver, Canada
- Contact   : hello@kennethormandy.com
##### Social Media:
- Twitter   : [@kennethormandy](https://twitter.com/kennethormandy)
- GitHub    : [@kennethormandy](https://github.com/kennethormandy)
- Url(s)    : [kennethormandy.com](http://kennethormandy.com)
##### Bio:

Kenneth Ormandy is a designer specialising in typography and front-end development. He works on [Surge](https://surge.sh) and [Harp](http://harpjs.com), organises [Vancouver’s typography meetup](http://typebrigade.com), and contributes to the [Lost Type Co-op](http://losttype.com).
##### Photo:

<img src="http://kennethormandy.com/images/kenneth-square.jpg" width="300px" alt="Avatar" />

**Comment by elyseholladay** [comment]
Hi Kenneth!

Thank you so much for submitting to SassConf this year!

Unfortunately, we weren’t able to select your talk. 

We had an incredible number of submissions this year: 81, in fact, enough to fill up over two weeks of Sassy goodness! But we only have two days, and we couldn’t pick everything.

If you have any questions at all about our selection process, your submission, or anything else at all, please reach out: elyse@sassconf.com and I’ll gladly give you more details.

Again, thank you for submitting. It’s people like you, who are willing to put themselves out there and work hard and submit and give talks that make it possible to even have SassConf. I hope you will submit again next year and continue to be part of the Sass community!

See you in November!
