### ISSUE TITLE
Ensuring the sustainability of your code learning community

### ISSUE THREAD

**Issue by rachelober** [SassConf/2015-austin-speaker-cfp#82]
# Ensuring the sustainability of your code learning community
## Type of Presentation (required)

[+] Standard Length Talk
[  ] Lightning Talk
[  ] Workshop
[  ] Moderated Discussion
## Description (required)

Most great epics tell of how against all odds, our heroine champions over incredible hurdles to accomplish their dream and create a massively successful project. I'm here to tell you that the story isn't over after the happily ever after. Instead, the hard work is just beginning. 

True legends don't form from one successful deploy, or one successful workshop run. Success is dictated by longevity and key points of interest. 

Now that you've figured out and climbed your mountain, how are you going to keep your project alive? How can you ensure stability?

In 2013, I set out with a very manageable goal of running a RailsBridge workshop in New York City. The second part of my goal was to create a self-sustaining organization that would continue to run workshops to teach the underrepresented minorities in tech while keeping the values set by the RailsBridge founders Sarah Mei and Sarah Allen. 

It's easy to run workshops, it's a lot harder to develop a healthy culture within a volunteer organization. 

In this talk I will highlight key points from my two years of as a RailsBridge chapter founder and go through the challenges I faced through strategies in real-time communication, documentation, and code curriculum sharing through technology.

The points highlighted are
- What is your mission statement?
- In one year what do you intend to accomplish?
- How do you measure success?
- Learning to collaborate and taking suggestions
- When to be aware that certain suggestions might not be helpful
- Always come back to your mission statement. Don't lose focus. 
- Planting seeds
- Getting comfortable with delegating
- When delegating doesn't work
- Learning when to let go
## Speaker Info (required)
- Name      : Rachel Ober
- Location  : Brooklyn, NY
- Contact   : rachelober@gmail.com
##### Social Media:
- Twitter   : [@rachelober](https://twitter.com/rachelober)
- GitHub    : [rachelober](url to GitHub account)
- Url(s)    : [rachelober.com](https://github.com/rachelober)
##### Bio:

Rachel Ober is a Ruby on Rails developer based in New York City. A true renaissance woman, Rachel has significant experience in and a passion for user experience, user interface and cognitive design. Rachel is a senior developer at Paperless Post where she serves as technical mentor for all front end developers on the development team and leads front end development for the company. She also teaches the ins and outs of Rails at General Assembly for their Back End Ruby on Rails course. Rachel encourages other women developers to hone their skills by contributing to the 3-day conference Write/Speak/Code as a co-organizer. Founded in 2013, Rachel organizes and volunteers her time teaching women Ruby and Ruby on Rails through RailsBridge NYC. Rachel lives in Brooklyn with her husband and fur-child Isabella and loves scrapbooking and card making.
##### Photo:

![Avatar](https://avatars3.githubusercontent.com/u/114306?v=3&s=460)

**Comment by misscs** [comment]
I think this would make a good moderated discussion, if Rachel is interested in presenting it in that format.

**Comment by elyseholladay** [comment]
Hi Rachel! 

Thank you so much for submitting to SassConf this year!

Unfortunately, we weren’t able to select your talk. 

We had an incredible number of submissions this year: 81, in fact, enough to fill up over two weeks of Sassy goodness! But we only have two days, and we couldn’t pick everything.

If you have any questions at all about our selection process, your submission, or anything else at all, please reach out: elyse@sassconf.com and I’ll gladly give you more details.

Again, thank you for submitting. It’s people like you, who are willing to put themselves out there and work hard and submit and give talks that make it possible to even have SassConf. I hope you will submit again next year and continue to be part of the Sass community!

See you in November!
