### ISSUE TITLE
Why you might want to remove compass from your project (and then want to add it back again)

### ISSUE THREAD

**Issue by rachelober** [SassConf/2015-austin-speaker-cfp#84]
# Why you might want to remove compass from your project (and then want to add it back again)
## Type of Presentation (required)

[x] Standard Length Talk
[  ] Lightning Talk
[  ] Workshop
[  ] Moderated Discussion
## Description (required)

At Paperless Post we are running on Rails 2.3.x. This year, one of our large initiatives is to upgrade to Rails 4 and all the gems that go with it. When taking an inventory, we found that we had issues automatically getting Compass updated. After analyzing our code, I found that we weren't really utilizing much of Compass' core functionality save for PNG spriting and CSS3 browser-specific mixins. By removing Compass, I could minimize our upgrade complexity by writing some custom mixins to replace those disappearing from the code base. However, when I dug deeper in to Compass to replace the methods we needed to keep, it dawned on me how little I really knew about Compass and found helpers and pieces of the code that could have helped the front end team attack issues we were having had we known tools were already written for us.

This talk will illustrate the reasons why you might want to remove Compass from your code base and what things you'd have to watch out for if you decide to do it — and then dig deeper in to why you might want to end up keeping it in to your project!
## Speaker Info (required)
- Name      : Rachel Ober
- Location  : Brooklyn, NY
- Contact   : rachelober@gmail.com
##### Social Media:
- Twitter   : [@rachelober](https://twitter.com/rachelober)
- GitHub    : [rachelober](url to GitHub account)
- Url(s)    : [rachelober.com](https://github.com/rachelober)
##### Bio:

Rachel Ober is a Ruby on Rails developer based in New York City. A true renaissance woman, Rachel has significant experience in and a passion for user experience, user interface and cognitive design. Rachel is a senior developer at Paperless Post where she serves as technical mentor for all front end developers on the development team and leads front end development for the company. She also teaches the ins and outs of Rails at General Assembly for their Back End Ruby on Rails course. Rachel encourages other women developers to hone their skills by contributing to the 3-day conference Write/Speak/Code as a co-organizer. Founded in 2013, Rachel organizes and volunteers her time teaching women Ruby and Ruby on Rails through RailsBridge NYC. Rachel lives in Brooklyn with her husband and fur-child Isabella and loves scrapbooking and card making.
##### Photo:

![Avatar](https://avatars3.githubusercontent.com/u/114306?v=3&s=460)

**Comment by misscs** [comment]
Removing Compass is a hot topic of discussion. I think this talk would be better suited for a technical lightning talk.

**Comment by elyseholladay** [comment]
Hi Rachel!

Thank you so much for submitting to SassConf this year!

Unfortunately, we weren’t able to select your talk. 

We had an incredible number of submissions this year: 81, in fact, enough to fill up over two weeks of Sassy goodness! But we only have two days, and we couldn’t pick everything.

If you have any questions at all about our selection process, your submission, or anything else at all, please reach out: elyse@sassconf.com and I’ll gladly give you more details.

Again, thank you for submitting. It’s people like you, who are willing to put themselves out there and work hard and submit and give talks that make it possible to even have SassConf. I hope you will submit again next year and continue to be part of the Sass community!

See you in November!
