### ISSUE TITLE
What's Wrong with Sass

### ISSUE THREAD

**Issue by GarthDB** [SassConf/2015-austin-speaker-cfp#85]
# What's Wrong with Sass
## Type of Presentation

[ x ] Standard Length Talk
[  ] Lightning Talk
[  ] Workshop
[  ] Moderated Discussion
## Description (required)

Hold up, before you object to the session title I should mention I love Sass; I'm already a convert.

Sass has changed the FED industry, it has helped us:
- to really rethink the way we organize our styles
- understand the power of preprocessors
- push CSS standards further
- think about performance
- consider maintenance
- become closer as a community

Keeping all that mind Sass is not perfect, and neither is the community. We are a group of imperfect people doing our best.

I think because Sass is so fantastic it is easy to become a Sass Fanatic. In our excitement for Sass we can end up shunning those who are using not Sass; intentionally or not.

My goal in this session isn't to tear Sass down, but to break the Sass dogma.

Here are some bullet points I'd like to flesh out more into a full session:
- Ruby Sass is not Libsass, so moving between Ruby to Node projects you can't always use the same Sass.
  - We could move Libsass to everywhere so we could always stay consistent, but there is real power in leaving preprocessors in the web languages. Mainly it makes is easier for the users of the preprocessors to make contributions back to the project.
- Consider the benefits of alternatives to Sass
  - Future CSS Standards
    - No build step needed in the future (less potential complexity)
    - Variable fallbacks
    - Color functions
    - `:matches`
    - `:not`
    - `rem` units everywhere
    - [CSS Next](http://cssnext.io/) as a polyfill
  - [Rework](https://github.com/reworkcss)
    - Build your own preprocessor - use only what you need, get the benefit of speed
    - Build plugins
    - [Myth](http://www.myth.io/) is built on Rework, helps to get started in a standard and simple way.
  - [PostCSS](https://github.com/postcss/postcss)
    - Fasterer
    - Great source mapping
    - Gaining popularity
  - [Less](http://lesscss.org/)
    - Guarded Mixins
    - Property merges
  - [Stylus](https://learnboost.github.io/stylus/)
    - Fast
    - Terse as hell
    - Forgiving
    - API

We don't need a single preprocessor to rule them all. These projects can learn from each other, and people can have different preferences; diversity is always a good thing.

Front end developers and designers should be trying new things, all the time. We should build education into our professional lives, and we should never be content with our current knowledge base or level of experience. Go forth and play with new things.

Don't do this at your day job, or at least not on large or existing projects. Start some side projects, contribute to open source projects, remake your own site, etc.
## Speaker Info (required)
- Name      : Garth Braithwaite
- Location  : Idaho Falls, ID
- Contact   : garthdb@gmail.com
##### Social Media:
- Twitter   : [@garthdb](http://twitter.com/garthdb)
- GitHub    : [garthdb](http://github.com/garthdb)
- Url(s)    : [garthdb.com](http://garthdb.com)
##### Bio:

Open Source Front End Designer and Developer at Adobe on the PhoneGap team.

Founder of [The Open Design Foundation](http://opendesign.foundation); host of the [Web Friends](http://webfriends.io) podcast
##### Photo:

![Avatar](http://www.gravatar.com/avatar/b5cf6e112eeee572d722743dea924487?s=500)

**Comment by thexavismith** [comment]
This looks like an awesome session! :+1:

**Comment by GarthDB** [comment]
Hey thanks @ttimsmith!

**Comment by scottkellum** [comment]
Thanks for submitting @GarthDB!

[Just read your tweet](https://twitter.com/garthdb/status/609034356074553345) and wanted to calm your nerves a bit.

The conversation you are bringing is one that has been popping up a lot lately and the introduction of a new styling language (like PostCSS) always seems to spark this sort of conversation. Sass has grown into its criticism with the creation of SCSS after LESS was released and Libsass to solve performance bugs and a language feature freeze to reach compatibility between Libsass and Ruby Sass along with work on a spec and Ruby Sass performance (Soooo close to 100% compatibility across Sass implementations).

You’re absolutely right that Sass isn’t perfect, what do you want people to get out of this talk? I think this is a conversation worth having. Most conversations I have seen along these lines has resulted in FUD which is why defining clear takeaways is important as well as research into the reasoning behind decisions or plans to address some of the criticism.

**Comment by GarthDB** [comment]
@scottkellum Thanks for the comment.

Yeah, the FUD is exactly what I want to avoid. The talk is aimed at encouraging Sass users to go out and try other tools and maybe even bring some of it back to Sass.

The talk is also supposed to have the goal of helping us all to be more inclusive. If we meet people who use Less, Stylus, PostCSS, etc, it's cool, we all write css and hopefully we're all pushing the web forward.

**Comment by scottkellum** [comment]
@GarthDB This all sounds really great actually. Maybe a title that gives positive encouragement for people to go try new things as the current one feels a bit FUD-y?

From my experience I am a big proponent of using PostCSS alongside Sass. There are CSS transformations it can do that are out of scope for Sass as a language and IMO it pairs beautifully with Sass to allow tons of control over production stylesheets. Not to sidestep Stylus either, lots of _really_ cool stuff there to talk about. LESS is ok, some people like the syntax better? :p

**Comment by misscs** [comment]
I'm very interested in having talks that explore alternatives to Sass. I like the way this is presented especially 

> My goal in this session isn't to tear Sass down, but to break the Sass dogma.

**Comment by elyseholladay** [comment]
Hi Garth! 

Thank you so much for submitting to SassConf this year!

Unfortunately, we weren’t able to select your talk. 

We had an incredible number of submissions this year: 81, in fact, enough to fill up over two weeks of Sassy goodness! But we only have two days, and we couldn’t pick everything.

If you have any questions at all about our selection process, your submission, or anything else at all, please reach out: elyse@sassconf.com and I’ll gladly give you more details.

Again, thank you for submitting. It’s people like you, who are willing to put themselves out there and work hard and submit and give talks that make it possible to even have SassConf. I hope you will submit again next year and continue to be part of the Sass community!

See you in November!
